#!/usr/bin/env python3
# AI-hint: Concurrent streaming Piper/Kokoro TTS audio synthesis and PipeWire buffer feeder (T-534, AGY-2132).
# AI-doc: usr/share/doc/mios/manual/ch79-streaming-tts-piper.md
"""Concurrent streaming Piper/Kokoro TTS audio synthesis and PipeWire buffer feeder.

Buffers incoming LLM text tokens, detects sentence and clause boundaries in real time,
synthesizes text chunks concurrently via local Piper/Kokoro ONNX or HTTP server,
and feeds raw PCM audio frames directly into low-latency PipeWire playback buffers
with sub-300ms time-to-first-sound latency.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import io
import json
import math
import os
import pathlib
import queue
import re
import select
import signal
import socket
import struct
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import wave
from typing import Any, Callable, Dict, Generator, Iterable, List, Optional, Tuple, Union

# ==============================================================================
# Audio & Engine Constants
# ==============================================================================

DEFAULT_SAMPLE_RATE = 24000
DEFAULT_CHANNELS = 1
BYTES_PER_SAMPLE = 2  # 16-bit signed PCM (s16le)
DEFAULT_BUFFER_SECONDS = 5.0
LATENCY_SLA_TARGET_MS = 300.0

DEFAULT_PIPER_URL = f"http://localhost:{os.environ.get('MIOS_PORT_PIPER', '8179')}"
DEFAULT_KOKORO_URL = f"{DEFAULT_PIPER_URL}/v1/audio/speech"  # [ports].piper serves Piper/Kokoro
DEFAULT_SOCKET_PATH = "/run/mios/audio-tts.sock"

SUPPORTED_ENGINES = ("piper", "kokoro")

DEFAULT_VOICES: Dict[str, str] = {
    "piper": "en_US-lessac-medium",
    "kokoro": "af_heart",
}

KNOWN_VOICES: Dict[str, List[str]] = {
    "piper": [
        "en_US-lessac-medium",
        "en_US-lessac-high",
        "en_US-lessac-low",
        "en_US-amy-medium",
        "en_US-amy-low",
        "en_US-ryan-medium",
        "en_US-ryan-high",
        "en_GB-alan-medium",
        "en_GB-southern_english_female-low",
    ],
    "kokoro": [
        "af_heart",
        "af_bella",
        "af_nicole",
        "af_sarah",
        "af_sky",
        "am_adam",
        "am_michael",
        "bf_emma",
        "bf_isabella",
        "bm_george",
        "bm_lewis",
    ],
}

# Common abbreviations that should not trigger sentence boundary splits
ABBREVIATIONS = {
    "mr", "mrs", "ms", "dr", "prof", "sr", "jr", "vs", "etc", "ie", "eg", "al", "dept", "st"
}


# ==============================================================================
# Validation Helpers
# ==============================================================================

def validate_engine(engine: str) -> str:
    """Validate TTS synthesis engine name."""
    engine_clean = (engine or "").strip().lower()
    if engine_clean not in SUPPORTED_ENGINES:
        raise ValueError(
            f"Unsupported engine '{engine}'. Supported engines: {', '.join(SUPPORTED_ENGINES)}"
        )
    return engine_clean


def validate_voice(voice: Optional[str], engine: str) -> str:
    """Validate voice model identifier for given engine."""
    engine_clean = validate_engine(engine)
    if not voice or not voice.strip():
        return DEFAULT_VOICES[engine_clean]

    voice_clean = voice.strip()

    # Allow custom path ending with .onnx or .bin
    if voice_clean.endswith(".onnx") or voice_clean.endswith(".bin"):
        return voice_clean

    known = KNOWN_VOICES.get(engine_clean, [])
    if voice_clean not in known:
        raise ValueError(
            f"Unsupported or invalid voice '{voice_clean}' for engine '{engine_clean}'. "
            f"Supported voices: {', '.join(known)}"
        )
    return voice_clean


def validate_text(text: str) -> str:
    """Validate input text prompt is non-empty."""
    cleaned = (text or "").strip()
    if not cleaned:
        raise ValueError("Cannot synthesize empty text prompt")
    return cleaned


# ==============================================================================
# Sentence & Clause Boundary Splitter
# ==============================================================================

class SentenceChunker:
    """Splits streamed text tokens into complete sentence and clause chunks.

    Enables concurrent synthesis of earlier sentences while subsequent text
    is still being streamed or generated by an LLM.
    """

    def __init__(self, max_clause_chars: int = 120):
        self.max_clause_chars = max_clause_chars
        self.buffer = ""

    def _is_abbreviation(self, text: str, dot_pos: int) -> bool:
        """Check if dot is part of a known abbreviation or decimal."""
        # Decimal check: e.g. 3.14
        if dot_pos > 0 and dot_pos + 1 < len(text):
            if text[dot_pos - 1].isdigit() and text[dot_pos + 1].isdigit():
                return True

        # Preceding word check
        start = dot_pos - 1
        while start >= 0 and (text[start].isalnum() or text[start] == "_"):
            start -= 1
        word = text[start + 1:dot_pos].lower()
        return word in ABBREVIATIONS

    def feed(self, chunk: str) -> List[str]:
        """Feed text token/chunk and return list of completed sentence chunks."""
        if not chunk:
            return []

        self.buffer += chunk
        emitted: List[str] = []

        while True:
            # Look for sentence boundaries: . ! ? \n
            split_idx = -1
            boundary_char_len = 1

            for i, ch in enumerate(self.buffer):
                if ch in (".", "!", "?"):
                    if ch == "." and self._is_abbreviation(self.buffer, i):
                        continue
                    # Check for trailing quotes or brackets
                    idx = i + 1
                    while idx < len(self.buffer) and self.buffer[idx] in ('"', "'", "”", "’", ")", "]", "}"):
                        idx += 1
                    # Ensure followed by whitespace or end of buffer if followed by capital
                    if idx >= len(self.buffer) or self.buffer[idx].isspace():
                        split_idx = idx
                        break
                elif ch == "\n":
                    split_idx = i + 1
                    break
                elif ch in (",", ";", ":") and i >= self.max_clause_chars:
                    # Clause boundary splitting on long sentences to keep latency low
                    split_idx = i + 1
                    break

            if split_idx != -1:
                sentence = self.buffer[:split_idx].strip()
                self.buffer = self.buffer[split_idx:].lstrip()
                if sentence:
                    emitted.append(sentence)
            else:
                break

        return emitted

    def flush(self) -> List[str]:
        """Flush remaining text in buffer."""
        emitted: List[str] = []
        sentence = self.buffer.strip()
        self.buffer = ""
        if sentence:
            emitted.append(sentence)
        return emitted


# ==============================================================================
# PipeWire Audio Buffer Feeder
# ==============================================================================

class AudioRingBuffer:
    """Thread-safe circular byte buffer for audio PCM streaming."""

    def __init__(self, capacity_bytes: int):
        self.capacity = max(capacity_bytes, 4096)
        self.buffer = bytearray(self.capacity)
        self.write_pos = 0
        self.read_pos = 0
        self.size = 0
        self.overflow_bytes = 0
        self.underruns = 0
        self.lock = threading.Lock()

    def write(self, data: bytes) -> int:
        """Write raw audio bytes into ring buffer."""
        if not data:
            return 0
        data_len = len(data)
        with self.lock:
            if self.size + data_len > self.capacity:
                discard = (self.size + data_len) - self.capacity
                self.overflow_bytes += discard
                self.read_pos = (self.read_pos + discard) % self.capacity
                self.size -= discard

            end_space = self.capacity - self.write_pos
            if data_len <= end_space:
                self.buffer[self.write_pos:self.write_pos + data_len] = data
            else:
                self.buffer[self.write_pos:self.capacity] = data[:end_space]
                self.buffer[0:data_len - end_space] = data[end_space:]

            self.write_pos = (self.write_pos + data_len) % self.capacity
            self.size += data_len
            return data_len

    def read(self, num_bytes: int) -> bytes:
        """Read and remove up to num_bytes from buffer."""
        with self.lock:
            read_len = min(num_bytes, self.size)
            if read_len <= 0:
                self.underruns += 1
                return b""

            end_space = self.capacity - self.read_pos
            if read_len <= end_space:
                data = bytes(self.buffer[self.read_pos:self.read_pos + read_len])
            else:
                first = self.buffer[self.read_pos:self.capacity]
                second = self.buffer[0:read_len - end_space]
                data = bytes(first + second)

            self.read_pos = (self.read_pos + read_len) % self.capacity
            self.size -= read_len
            return data

    def available(self) -> int:
        with self.lock:
            return self.size

    def clear(self) -> None:
        with self.lock:
            self.write_pos = 0
            self.read_pos = 0
            self.size = 0


class PipeWireAudioFeeder:
    """Feeds synthesized PCM audio frames into PipeWire playback buffer."""

    def __init__(
        self,
        sample_rate: int = DEFAULT_SAMPLE_RATE,
        channels: int = DEFAULT_CHANNELS,
        mock_mode: bool = False,
        dry_run: bool = False,
        output_file: Optional[str] = None,
        verbose: bool = False,
    ):
        self.sample_rate = sample_rate
        self.channels = channels
        self.mock_mode = mock_mode
        self.dry_run = dry_run
        self.output_file = output_file
        self.verbose = verbose

        capacity_bytes = int(sample_rate * DEFAULT_BUFFER_SECONDS * BYTES_PER_SAMPLE * channels)
        self.ring_buffer = AudioRingBuffer(capacity_bytes)
        self.total_bytes_written = 0
        self.total_frames_written = 0
        self.first_sound_time: Optional[float] = None
        self.feed_start_time: Optional[float] = None
        self.underruns_count = 0

        self.proc: Optional[subprocess.Popen] = None
        self.file_sink: Optional[io.BytesIO] = None
        self.is_open = False

    def log(self, msg: str) -> None:
        if self.verbose:
            print(f"[mios-audio-tts] {msg}", file=sys.stderr)

    def start(self) -> None:
        """Start audio playback stream."""
        if self.is_open:
            return
        self.feed_start_time = time.perf_counter()
        self.is_open = True

        if self.dry_run:
            self.log("PipeWireAudioFeeder started (dry-run)")
            return

        if self.output_file:
            self.file_sink = io.BytesIO()

        if not self.mock_mode:
            # Check for pw-play / paplay / aplay
            cmd = None
            if self._has_binary("pw-play"):
                cmd = [
                    "pw-play",
                    "--format", "s16le",
                    "--rate", str(self.sample_rate),
                    "--channels", str(self.channels),
                    "-",
                ]
            elif self._has_binary("paplay"):
                cmd = [
                    "paplay",
                    "--raw",
                    "--format=s16le",
                    f"--rate={self.sample_rate}",
                    f"--channels={self.channels}",
                ]
            elif self._has_binary("aplay"):
                cmd = [
                    "aplay",
                    "-q",
                    "-r", str(self.sample_rate),
                    "-f", "S16_LE",
                    "-c", str(self.channels),
                ]

            if cmd:
                try:
                    self.proc = subprocess.Popen(
                        cmd,
                        stdin=subprocess.PIPE,
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                    self.log(f"Spawned audio playback pipeline: {' '.join(cmd)}")
                except OSError as err:
                    self.log(f"Failed to spawn audio pipeline: {err}; fallback to mock buffer")
                    self.proc = None

    def _has_binary(self, name: str) -> bool:
        return any(
            os.path.isfile(os.path.join(p, name)) and os.access(os.path.join(p, name), os.X_OK)
            for p in os.environ.get("PATH", "").split(os.pathsep)
        )

    def feed_pcm(self, pcm_bytes: bytes) -> int:
        """Feed PCM audio bytes to PipeWire buffer."""
        if not pcm_bytes:
            return 0

        now = time.perf_counter()
        if self.first_sound_time is None:
            self.first_sound_time = now

        # Alignment verification (must be even bytes for 16-bit)
        if len(pcm_bytes) % BYTES_PER_SAMPLE != 0:
            pcm_bytes = pcm_bytes[:len(pcm_bytes) - (len(pcm_bytes) % BYTES_PER_SAMPLE)]

        if not pcm_bytes:
            return 0

        # Buffer telemetry
        written = self.ring_buffer.write(pcm_bytes)
        self.total_bytes_written += written
        self.total_frames_written += written // (BYTES_PER_SAMPLE * self.channels)

        if self.output_file and self.file_sink:
            self.file_sink.write(pcm_bytes)

        if self.proc and self.proc.stdin:
            try:
                self.proc.stdin.write(pcm_bytes)
                self.proc.stdin.flush()
            except (BrokenPipeError, OSError) as err:
                self.log(f"PipeWire feed error: {err}")
                self.underruns_count += 1

        return written

    def close(self) -> None:
        """Close playback stream and flush files if required."""
        if not self.is_open:
            return
        self.is_open = False

        if self.proc:
            try:
                if self.proc.stdin:
                    self.proc.stdin.close()
                self.proc.wait(timeout=2.0)
            except Exception:
                try:
                    self.proc.kill()
                except Exception:
                    pass
            self.proc = None

        if self.output_file and self.file_sink:
            try:
                pcm_data = self.file_sink.getvalue()
                if self.output_file.lower().endswith(".wav"):
                    with wave.open(self.output_file, "wb") as wf:
                        wf.setnchannels(self.channels)
                        wf.setsampwidth(BYTES_PER_SAMPLE)
                        wf.setframerate(self.sample_rate)
                        wf.writeframes(pcm_data)
                else:
                    with open(self.output_file, "wb") as f:
                        f.write(pcm_data)
                self.log(f"Saved audio output to {self.output_file}")
            except OSError as err:
                self.log(f"Failed to write output file: {err}")

    def get_metrics(self) -> Dict[str, Any]:
        """Return feeder statistics and latency SLA metrics."""
        ttfs_ms = 0.0
        if self.first_sound_time is not None and self.feed_start_time is not None:
            ttfs_ms = round((self.first_sound_time - self.feed_start_time) * 1000.0, 2)

        return {
            "sample_rate": self.sample_rate,
            "channels": self.channels,
            "bytes_written": self.total_bytes_written,
            "frames_written": self.total_frames_written,
            "duration_sec": round(self.total_frames_written / max(self.sample_rate, 1), 2),
            "buffer_capacity_bytes": self.ring_buffer.capacity,
            "buffer_occupancy_bytes": self.ring_buffer.available(),
            "underruns": self.underruns_count + self.ring_buffer.underruns,
            "time_to_first_sound_ms": ttfs_ms,
            "target_met": ttfs_ms <= LATENCY_SLA_TARGET_MS if ttfs_ms > 0 else True,
        }


# ==============================================================================
# Synthesis Engines (Mock, HTTP, ONNX)
# ==============================================================================

def generate_mock_pcm(
    text: str,
    sample_rate: int = DEFAULT_SAMPLE_RATE,
    frequency: float = 330.0,
    amplitude: float = 0.4,
) -> bytes:
    """Generate synthetic PCM waveform for mock synthesis."""
    # Approximate speech duration: ~80ms per word, minimum 150ms
    word_count = max(1, len(text.split()))
    duration_sec = max(0.15, min(3.0, word_count * 0.12))
    total_samples = int(sample_rate * duration_sec)

    frames = bytearray()
    for i in range(total_samples):
        t = float(i) / float(sample_rate)
        # Modulated sine wave for natural acoustic spectrum
        mod = 1.0 + 0.2 * math.sin(2.0 * math.pi * 5.0 * t)
        val = amplitude * mod * 32767.0 * math.sin(2.0 * math.pi * frequency * t)
        sample = max(-32768, min(32767, int(val)))
        frames.extend(struct.pack("<h", sample))

    return bytes(frames)


class BaseSynthesisEngine:
    def synthesize_chunk(self, text: str, voice: str) -> bytes:
        raise NotImplementedError


class MockSynthesisEngine(BaseSynthesisEngine):
    """Deterministic, ultra-fast mock synthesis engine for tests and CI."""

    def __init__(self, sample_rate: int = DEFAULT_SAMPLE_RATE, latency_sim_sec: float = 0.015):
        self.sample_rate = sample_rate
        self.latency_sim_sec = latency_sim_sec

    def synthesize_chunk(self, text: str, voice: str) -> bytes:
        # Simulate realistic fast GPU/ONNX inference (<25ms)
        if self.latency_sim_sec > 0:
            time.sleep(self.latency_sim_sec)
        return generate_mock_pcm(text, sample_rate=self.sample_rate)


class HttpSynthesisEngine(BaseSynthesisEngine):
    """Bridges synthesis to local Piper / Kokoro HTTP service."""

    def __init__(
        self,
        endpoint_url: str,
        engine: str = "piper",
        sample_rate: int = DEFAULT_SAMPLE_RATE,
        timeout: float = 10.0,
        verbose: bool = False,
    ):
        self.endpoint_url = endpoint_url
        self.engine = engine
        self.sample_rate = sample_rate
        self.timeout = timeout
        self.verbose = verbose

    def synthesize_chunk(self, text: str, voice: str) -> bytes:
        headers = {"Content-Type": "application/json"}
        if self.engine == "piper":
            # Piper HTTP accepts raw text in query or JSON
            url = f"{self.endpoint_url.rstrip('/')}/"
            payload = json.dumps({"text": text, "voice": voice}).encode("utf-8")
        else:
            # Kokoro / OpenAI-compatible /v1/audio/speech
            url = self.endpoint_url
            payload = json.dumps({
                "model": "kokoro",
                "input": text,
                "voice": voice,
                "response_format": "pcm",
            }).encode("utf-8")

        req = urllib.request.Request(url, data=payload, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                data = resp.read()
                # Check if WAV and strip header if needed, or raw PCM
                if data.startswith(b"RIFF"):
                    # Extract raw PCM from WAV
                    with wave.open(io.BytesIO(data), "rb") as wf:
                        return wf.readframes(wf.getnframes())
                return data
        except (urllib.error.URLError, OSError) as err:
            if self.verbose:
                print(f"[mios-audio-tts] HTTP synthesis failed: {err}", file=sys.stderr)
            raise RuntimeError(f"HTTP synthesis failed connecting to {url}: {err}")


# ==============================================================================
# Streaming TTS Worker Orchestrator
# ==============================================================================

class StreamingTTSWorker:
    """Coordinates text streaming, sentence splitting, concurrent synthesis, and PipeWire feeding."""

    def __init__(
        self,
        engine: str = "piper",
        voice: Optional[str] = None,
        sample_rate: int = DEFAULT_SAMPLE_RATE,
        mock_mode: bool = False,
        dry_run: bool = False,
        output_file: Optional[str] = None,
        verbose: bool = False,
        piper_url: str = DEFAULT_PIPER_URL,
        kokoro_url: str = DEFAULT_KOKORO_URL,
    ):
        self.engine = validate_engine(engine)
        self.voice = validate_voice(voice, self.engine)
        self.sample_rate = sample_rate
        self.mock_mode = mock_mode
        self.dry_run = dry_run
        self.output_file = output_file
        self.verbose = verbose

        self.chunker = SentenceChunker()
        self.feeder = PipeWireAudioFeeder(
            sample_rate=sample_rate,
            channels=DEFAULT_CHANNELS,
            mock_mode=mock_mode,
            dry_run=dry_run,
            output_file=output_file,
            verbose=verbose,
        )

        if mock_mode or dry_run:
            self.synthesis_engine: BaseSynthesisEngine = MockSynthesisEngine(sample_rate=sample_rate)
        else:
            url = piper_url if self.engine == "piper" else kokoro_url
            self.synthesis_engine = HttpSynthesisEngine(
                endpoint_url=url,
                engine=self.engine,
                sample_rate=sample_rate,
                verbose=verbose,
            )

        self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=4)
        self.pending_futures: List[Tuple[int, str, concurrent.futures.Future]] = []
        self.chunk_index = 0
        self.running = False

    def log(self, msg: str) -> None:
        if self.verbose:
            print(f"[mios-audio-tts] {msg}", file=sys.stderr)

    def _submit_sentence(self, sentence: str) -> None:
        """Submit sentence chunk to concurrent synthesis worker."""
        if not sentence.strip():
            return

        idx = self.chunk_index
        self.chunk_index += 1
        self.log(f"Submitting chunk {idx} for synthesis: '{sentence}'")

        future = self.executor.submit(
            self.synthesis_engine.synthesize_chunk,
            sentence,
            self.voice,
        )
        self.pending_futures.append((idx, sentence, future))

    def _drain_ready_audio(self, wait_all: bool = False) -> int:
        """Drain synthesized audio chunks in sequential order and feed to PipeWire."""
        fed_chunks = 0
        while self.pending_futures:
            idx, sentence, future = self.pending_futures[0]
            if wait_all or future.done():
                self.pending_futures.pop(0)
                try:
                    pcm_data = future.result()
                    self.feeder.feed_pcm(pcm_data)
                    fed_chunks += 1
                    self.log(f"Fed chunk {idx} ({len(pcm_data)} bytes) to audio buffer")
                except Exception as err:
                    self.log(f"Synthesis failed for chunk {idx}: {err}")
                    if not self.mock_mode:
                        raise
            else:
                break
        return fed_chunks

    def feed_token(self, token: str) -> int:
        """Feed incremental text token from LLM or socket."""
        sentences = self.chunker.feed(token)
        for s in sentences:
            self._submit_sentence(s)

        return self._drain_ready_audio(wait_all=False)

    def flush(self) -> int:
        """Flush remaining text buffer and wait for all synthesis tasks to complete."""
        remaining = self.chunker.flush()
        for s in remaining:
            self._submit_sentence(s)

        return self._drain_ready_audio(wait_all=True)

    def speak(self, text: str) -> Dict[str, Any]:
        """Perform one-shot speech synthesis of text prompt."""
        cleaned_text = validate_text(text)
        self.feeder.start()
        try:
            self.feed_token(cleaned_text)
            self.flush()
        finally:
            self.feeder.close()

        return self.get_status()

    def stream_from_iterable(self, token_iter: Iterable[str]) -> Dict[str, Any]:
        """Stream speech synthesis from token iterable."""
        self.feeder.start()
        try:
            for token in token_iter:
                self.feed_token(token)
            self.flush()
        finally:
            self.feeder.close()

        return self.get_status()

    def stream_from_socket(self, sock_path: str = DEFAULT_SOCKET_PATH, timeout: Optional[float] = None) -> None:
        """Run Unix domain socket listener for incoming streaming text tokens."""
        sock_dir = os.path.dirname(sock_path)
        if sock_dir and not os.path.exists(sock_dir):
            try:
                os.makedirs(sock_dir, exist_ok=True)
            except OSError:
                sock_path = f"/tmp/audio-tts-{os.getuid()}.sock"

        if os.path.exists(sock_path):
            try:
                os.unlink(sock_path)
            except OSError:
                pass

        server_sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        server_sock.bind(sock_path)
        server_sock.listen(5)
        server_sock.setblocking(False)
        self.log(f"Listening for text streams on {sock_path}")

        self.running = True

        def sig_handler(sig, frame):
            self.running = False

        if threading.current_thread() is threading.main_thread():
            try:
                signal.signal(signal.SIGINT, sig_handler)
                signal.signal(signal.SIGTERM, sig_handler)
            except (ValueError, AttributeError):
                pass

        start_time = time.time()
        clients: List[socket.socket] = []

        try:
            while self.running:
                if timeout and (time.time() - start_time) >= timeout:
                    break

                readable, _, _ = select.select([server_sock] + clients, [], [], 0.05)
                for s in readable:
                    if s is server_sock:
                        client, _ = server_sock.accept()
                        client.setblocking(False)
                        clients.append(client)
                        self.feeder.start()
                        self.log("Accepted text streaming client")
                    else:
                        try:
                            data = s.recv(4096)
                            if not data:
                                clients.remove(s)
                                s.close()
                                self.flush()
                                continue
                            text = data.decode("utf-8", errors="replace")
                            self.feed_token(text)
                        except (BlockingIOError, ConnectionResetError):
                            if s in clients:
                                clients.remove(s)
                                s.close()
        finally:
            for c in clients:
                try:
                    c.close()
                except Exception:
                    pass
            try:
                server_sock.close()
                if os.path.exists(sock_path):
                    os.unlink(sock_path)
            except Exception:
                pass
            self.feeder.close()

    def get_status(self) -> Dict[str, Any]:
        """Return comprehensive engine status, buffer statistics, and latency SLA."""
        feeder_metrics = self.feeder.get_metrics()
        return {
            "engine": self.engine,
            "voice": self.voice,
            "supported_engines": list(SUPPORTED_ENGINES),
            "supported_voices": KNOWN_VOICES.get(self.engine, []),
            "mock_mode": self.mock_mode,
            "dry_run": self.dry_run,
            "chunks_synthesized": self.chunk_index,
            "latency_sla_target_ms": LATENCY_SLA_TARGET_MS,
            **feeder_metrics,
            "status": "healthy" if feeder_metrics["underruns"] == 0 else "degraded",
        }


# ==============================================================================
# CLI Entry Point
# ==============================================================================

def build_parser() -> argparse.ArgumentParser:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("-v", "--verbose", action="store_true", default=argparse.SUPPRESS, help="Enable verbose diagnostic logs")
    common.add_argument("--dry-run", action="store_true", default=argparse.SUPPRESS, help="Validate configuration and parameters without executing audio")
    common.add_argument("--mock", action="store_true", default=argparse.SUPPRESS, help="Enable mock audio synthesis and playback loopback")
    common.add_argument("--sample-rate", type=int, default=argparse.SUPPRESS, help=f"Audio sample rate in Hz (default: {DEFAULT_SAMPLE_RATE})")
    common.add_argument("--engine", choices=list(SUPPORTED_ENGINES), default=argparse.SUPPRESS, help="TTS synthesis engine (piper or kokoro)")
    common.add_argument("--voice", default=argparse.SUPPRESS, help="Voice model identifier")
    common.add_argument("--output", default=argparse.SUPPRESS, help="Save synthesized audio to file (.wav or raw PCM)")

    parser = argparse.ArgumentParser(
        prog="mios_audio_tts.py",
        description="Concurrent streaming Piper/Kokoro TTS audio synthesis and PipeWire buffer feeder (T-534, AGY-2132).",
        parents=[common],
    )

    subparsers = parser.add_subparsers(dest="subcommand", help="Operational modes")

    # Subcommand: stream
    stream_parser = subparsers.add_parser("stream", parents=[common], help="Stream speech synthesis from stdin, file, or socket")
    stream_parser.add_argument("--input", "-i", default="-", help="Input text path or '-' for stdin (default: -)")
    stream_parser.add_argument("--socket", default=None, help="Unix domain socket path to bind for streaming")
    stream_parser.add_argument("--timeout", type=float, default=None, help="Timeout in seconds for daemon operation")

    # Subcommand: speak
    speak_parser = subparsers.add_parser("speak", parents=[common], help="One-shot speech synthesis of text argument")
    speak_parser.add_argument("text", help="Text prompt to synthesize into audio")

    # Subcommand: status
    subparsers.add_parser("status", parents=[common], help="Report TTS engine connection, buffer stats, and voice models")

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    if not args.subcommand:
        parser.print_help()
        return 0

    verbose = getattr(args, "verbose", False)
    dry_run = getattr(args, "dry_run", False)
    mock_mode = getattr(args, "mock", False)
    sample_rate = getattr(args, "sample_rate", DEFAULT_SAMPLE_RATE)
    raw_engine = getattr(args, "engine", "piper")
    raw_voice = getattr(args, "voice", None)
    output_file = getattr(args, "output", None)

    try:
        engine = validate_engine(raw_engine)
        voice = validate_voice(raw_voice, engine)
    except ValueError as err:
        print(f"Error: {err}", file=sys.stderr)
        return 1

    if args.subcommand == "status":
        worker = StreamingTTSWorker(
            engine=engine,
            voice=voice,
            sample_rate=sample_rate,
            mock_mode=mock_mode,
            dry_run=dry_run,
            verbose=verbose,
        )
        status_data = worker.get_status()
        print(json.dumps(status_data, indent=2))
        return 0

    elif args.subcommand == "speak":
        try:
            cleaned_text = validate_text(args.text)
        except ValueError as err:
            print(f"Error: {err}", file=sys.stderr)
            return 1

        if dry_run:
            print("[mios-audio-tts] Dry-run validated: speak command parameters OK")
            print(f"  Engine: {engine}")
            print(f"  Voice: {voice}")
            print(f"  Text: '{cleaned_text}'")
            print(f"  Mock mode: {mock_mode}")
            return 0

        worker = StreamingTTSWorker(
            engine=engine,
            voice=voice,
            sample_rate=sample_rate,
            mock_mode=mock_mode,
            dry_run=dry_run,
            output_file=output_file,
            verbose=verbose,
        )
        try:
            status = worker.speak(cleaned_text)
            if verbose:
                print(f"[mios-audio-tts] Synthesis complete: {json.dumps(status)}", file=sys.stderr)
            return 0
        except Exception as err:
            print(f"Error during speech synthesis: {err}", file=sys.stderr)
            return 1

    elif args.subcommand == "stream":
        if dry_run:
            print("[mios-audio-tts] Dry-run validated: stream command parameters OK")
            print(f"  Engine: {engine}")
            print(f"  Voice: {voice}")
            print(f"  Input: {args.input}")
            print(f"  Socket: {args.socket}")
            print(f"  Mock mode: {mock_mode}")
            return 0

        worker = StreamingTTSWorker(
            engine=engine,
            voice=voice,
            sample_rate=sample_rate,
            mock_mode=mock_mode,
            dry_run=dry_run,
            output_file=output_file,
            verbose=verbose,
        )

        if args.socket:
            worker.stream_from_socket(sock_path=args.socket, timeout=args.timeout)
            return 0
        else:
            # Read from file or stdin
            def token_generator() -> Generator[str, None, None]:
                if args.input == "-":
                    for line in sys.stdin:
                        yield line
                else:
                    if not os.path.exists(args.input):
                        raise FileNotFoundError(f"Input file not found: {args.input}")
                    with open(args.input, "r", encoding="utf-8") as f:
                        for line in f:
                            yield line

            try:
                status = worker.stream_from_iterable(token_generator())
                if verbose:
                    print(f"[mios-audio-tts] Stream complete: {json.dumps(status)}", file=sys.stderr)
                return 0
            except Exception as err:
                print(f"Error during streaming synthesis: {err}", file=sys.stderr)
                return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
