# AI-hint: stub
# AI-related: stub
[package]
name = "miosd"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["cargo"] }
toml.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
regex.workspace = true
tokio.workspace = true
libc.workspace = true
mios-build = { path = "../mios-build" }
mios-config = { path = "../mios-config" }

[dev-dependencies]
tempfile.workspace = true

