# SPDX-License-Identifier: Apache-2.0
# AI-hint: Kdump configuration for automated zstd crash dump extraction (T-515).
# AI-doc: usr/share/doc/mios/manual/ch02-architecture.md
path /var/crash
core_collector makedumpfile -l --message-level 1 -d 31
extra_modules zstd
default reboot
