// AI-hint: TASKS.md renderer -- byte-deterministic documentation of tasks.jsonl under the '# TASKS' banner, around the verbatim operator-overrides block; no dates, no timestamps.
// AI-related: tasks.jsonl, TASKS.md, /usr/share/mios/mios.toml [tasks.store], tools/native/mios-task/src/overrides.rs
// AI-functions: render, empty_block, line

use crate::overrides::{Effective, BANNER, BEGIN, END};
use crate::record::STATUSES;
use serde_json::Value;
use std::collections::BTreeMap;

/// A group heading that sorts named groups before the unnamed one.
type SortKey = (u8, String);

/// The block a first render writes: one comment saying what a line looks like, no override.
pub fn empty_block() -> String {
    "<!-- One JSON object per line: {\"id\": \"T-001\", \"status\": \"incomplete\", \"owner\": \"operator\"}. \
Its fields are applied on top of the record whenever a task tool reads the list. -->\n"
        .to_string()
}

fn s<'a>(r: &'a Value, k: &str) -> &'a str {
    r.get(k).and_then(|x| x.as_str()).unwrap_or("")
}

fn one_line(t: &str) -> String {
    t.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// TASKS.md for `eff`, with `inner` (the bytes between the override markers) copied verbatim.
pub fn render(store: &str, eff: &Effective, inner: &str) -> String {
    let mut o = String::new();
    o.push_str(BANNER);
    o.push_str("\n\n");
    o.push_str(&format!(
        "<!-- GENERATED by `mios-task render` from {store}. Do not edit this file outside the overrides block: \
change tasks in {store} (mios-task add/set/claim, or the dev-loop task tools), or add an override line below, \
then run `mios-task render`. `mios-task check` fails on any other difference. -->\n\n"
    ));
    o.push_str(&format!(
        "`{store}` at the repo root is the only canonical MiOS task list (ADR-0028). This file is its generated \
documentation. The two edit surfaces are `{store}` and the operator-overrides block below; every task reader \
(mios-task check, render, ready/next, claim, set, and the dev-loop task tools) applies the overrides on top of \
`{store}`.\n\n"
    ));
    o.push_str("## Operator overrides\n\n");
    o.push_str(&format!(
        "Each line between the markers that starts with `{{` is one override: a JSON object with an `\"id\"` and the \
record fields to apply (`status` in either dialect). The last line wins per (id, field); an unknown id, an unknown \
field or a value the schema refuses fails `mios-task check`. `mios-task overrides fold <id>` moves an override \
into `{store}`. Fields shown with `[override]` below come from this block.\n\n"
    ));
    o.push_str(BEGIN);
    o.push('\n');
    o.push_str(inner);
    o.push_str(END);
    o.push_str("\n\n");

    let mut counts: BTreeMap<&str, usize> = BTreeMap::new();
    for r in &eff.records {
        *counts.entry(s(r, "status")).or_default() += 1;
    }
    o.push_str("## Summary\n\n| Status | Records |\n|---|---|\n");
    for st in STATUSES {
        o.push_str(&format!(
            "| {st} | {} |\n",
            counts.get(st).copied().unwrap_or(0)
        ));
    }
    o.push_str(&format!("| total | {} |\n", eff.records.len()));
    o.push_str(&format!(
        "\n{} record(s) carry at least one override.\n",
        eff.overridden.len()
    ));

    // Workstream, then epic, then file order.
    let mut groups: BTreeMap<SortKey, BTreeMap<SortKey, Vec<&Value>>> = BTreeMap::new();
    for r in &eff.records {
        let ws = r.get("workstream").and_then(|x| x.as_str()).unwrap_or("");
        let wk = if ws.is_empty() {
            (1, "(no workstream)".to_string())
        } else {
            (0, one_line(ws))
        };
        let ep = s(r, "epic");
        let ek = if ep.is_empty() {
            (0, String::new())
        } else {
            (1, ep.to_string())
        };
        groups.entry(wk).or_default().entry(ek).or_default().push(r);
    }
    for ((_, ws), epics) in &groups {
        o.push_str(&format!("\n## {ws}\n"));
        for ((_, ep), recs) in epics {
            if ep.is_empty() {
                o.push_str("\n### No epic\n\n");
            } else {
                o.push_str(&format!("\n### Epic {ep}\n\n"));
            }
            for r in recs {
                o.push_str(&line(r, eff));
                o.push('\n');
            }
        }
    }
    o
}

fn line(r: &Value, eff: &Effective) -> String {
    let id = s(r, "id");
    let ov = eff.overridden.get(id);
    let tag = |f: &str| {
        if ov.is_some_and(|x| x.contains(f)) {
            " [override]"
        } else {
            ""
        }
    };
    let mut parts = vec![format!("{}{}", s(r, "status"), tag("status"))];
    let owner = s(r, "owner");
    if !owner.is_empty() || !tag("owner").is_empty() {
        let shown = if owner.is_empty() {
            "(unclaimed)"
        } else {
            owner
        };
        parts.push(format!("owner {}{}", shown, tag("owner")));
    }
    if let Some(p) = r.get("priority").and_then(|x| x.as_str()) {
        parts.push(format!("{p}{}", tag("priority")));
    }
    if let Some(z) = r.get("size").and_then(|x| x.as_str()) {
        parts.push(format!("size {z}{}", tag("size")));
    }
    let deps: Vec<&str> = r
        .get("depends_on")
        .and_then(|d| d.as_array())
        .map(|a| a.iter().filter_map(|x| x.as_str()).collect())
        .unwrap_or_default();
    if !deps.is_empty() || !tag("depends_on").is_empty() {
        parts.push(format!(
            "depends_on {}{}",
            deps.join(", "),
            tag("depends_on")
        ));
    }
    let shown_elsewhere = ["id", "status", "owner", "priority", "size", "depends_on"];
    if let Some(fields) = ov {
        let rest: Vec<&str> = fields
            .iter()
            .map(String::as_str)
            .filter(|f| !shown_elsewhere.contains(f))
            .collect();
        if !rest.is_empty() {
            parts.push(format!("{} [override]", rest.join(", ")));
        }
    }
    format!(
        "- `{id}` {} -- {}",
        one_line(s(r, "title")),
        parts.join(" · ")
    )
}
