#!/usr/bin/env bash
# AI-hint: Single devcontainer lifecycle entrypoint: create, start, and platform setup retain the original ordered hooks and fail behavior.
set -euo pipefail

# The lifecycle commands run in the devcontainer's workspaceFolder, which is the
# [workspace] root holding every MiOS repo, not this repo; the relative paths
# below (.devloop_artifacts, harness/) are this repo's.
cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.."

mios_platform() {
    local platform config_dir
    if [[ -n "${CODESPACES:-}" ]]; then
        platform=codespaces
    elif [[ "${CLOUD_SHELL:-}" == "true" ]]; then
        platform=google-cloud-shell
    elif [[ -f /etc/oracle-release || -n "${OCI_CLI_CONFIG_FILE:-}" ]]; then
        platform=oracle-cloud-shell
    else
        platform=generic-devcontainer
    fi

    config_dir="${HOME}/.config/mios"
    install -d -m 0755 "${config_dir}"
    cat > "${config_dir}/devcontainer.env" <<EOF
# Generated by MiOS Dev Container post-create.
MIOS_DEVELOPMENT_PLATFORM=${platform}
MIOS_ARTIFACT_PROFILE=portable
EOF

    echo "[devcontainer:platform] ${platform}: portable MiOS development core configured."
    echo "[devcontainer:platform] Use .devcontainer/artifact-builder on a trusted host for privileged disk artifacts."
}

mios_core() {
    local root=/workspaces/MiOS
    local rust_manifest="${root}/src/mios-rs/Cargo.toml"
    local install_dir=/opt/mios/bin
    local agent_pipe_python=/usr/lib/mios/agents/.venv/bin/python
    local binary

    if [[ ! -f "${rust_manifest}" ]]; then
        echo "[devcontainer:core] Missing miosd workspace manifest: ${rust_manifest}" >&2
        return 1
    fi
    if [[ ! -x "${agent_pipe_python}" ]]; then
        echo "[devcontainer:core] Missing agent-pipe runtime: ${agent_pipe_python}" >&2
        return 1
    fi

    echo "[devcontainer:core] Verifying agent-pipe runtime..."
    "${agent_pipe_python}" -c 'import fastapi, httpx, mcp, pydantic, uvicorn'

    echo "[devcontainer:core] Initializing MiOS developer state..."
    install -d -m 0755 \
        "${HOME}/.local/state/mios/agent-pipe" \
        "${HOME}/.local/state/mios/daemon" \
        "${HOME}/.local/share/mios/agent-pipe" \
        "${HOME}/.cache/mios/agent-pipe"

    echo "[devcontainer:core] Building upstream native workspaces..."
    (cd "${root}/src/mios-rs" && cargo build --release)
    (cd "${root}/tools/native" && cargo build --release --workspace --exclude mios-wallpaperd)
    sudo install -d -m 0755 "${install_dir}"
    for binary in \
        "${root}"/src/mios-rs/target/release/mios* \
        "${root}"/tools/native/target/release/mios-* \
        "${root}"/tools/native/target/release/generate-names-registry; do
        [[ -x "${binary}" ]] || continue
        sudo install -m 0755 "${binary}" "${install_dir}/$(basename "${binary}")"
    done
    sudo ln -sfn "${install_dir}/miosd" /usr/local/bin/miosd
    miosd --help >/dev/null

    echo "[devcontainer:core] MiOS development core is ready."
}

mios_create() {
    echo "[devcontainer:post-create] Initializing embedded agent harness..."
    mkdir -p .devloop_artifacts .worktrees
    git config --global --add safe.directory /workspaces/MiOS
    bash /workspaces/MiOS/.devcontainer/setup-devcontainer.sh
    mios_core
    echo "[devcontainer:post-create] Full MiOS workspace and harness are ready."
}

mios_start() {
    readonly ROOT=/workspaces/MiOS

    if ! git -C "$ROOT" rev-parse --git-dir >/dev/null 2>&1; then
        echo "[devcontainer:boot] MiOS workspace is unavailable: ${ROOT}" >&2
        exit 1
    fi
    if ! command -v sudo >/dev/null 2>&1; then
        echo "[devcontainer:boot] sudo is required to apply the MiOS root overlay" >&2
        exit 1
    fi

    echo "[devcontainer:boot] Applying MiOS system overlay..."
    sudo bash "${ROOT}/.devcontainer/install-root-overlay.sh"

    echo "[devcontainer:boot] Reconciling MiOS development core..."
    mios_core
    mios_platform
    mios-agent-pipe-dev start
    /usr/lib/mios/mcp/.venv/bin/python3 /usr/libexec/mios/mios-mcp-server --project-agent-clients

    # Re-seed the live editor Machine/settings.json from .dotfiles on every start:
    # these paths are regenerated by the client on reconnect/version-bump and drop
    # the theme/frameless projection applied by postCreateCommand exactly once.
    echo "[devcontainer:boot] Re-projecting .dotfiles SSOT into the live editor profile..."
    python3 "${ROOT}/tools/sync-dotfiles.py" || echo "[devcontainer:boot] sync-dotfiles.py failed; continuing" >&2

    for required in podman bootc miosd; do
        if ! command -v "${required}" >/dev/null 2>&1; then
            echo "[devcontainer:boot] Missing required MiOS component: ${required}" >&2
            exit 1
        fi
    done

    echo "[devcontainer:boot] MiOS systems are installed and ready."
}

mios_post_start() {
    echo "[devcontainer:post-start] Checking agentic environment and AI endpoint..."

    # postCreateCommand only ever runs once per container lifetime, so a
    # transient network failure there (e.g. agy's release-manifest endpoint
    # unreachable at creation time) would otherwise never be retried. Re-check
    # and self-heal on every start instead; best-effort, never fails the gate.
    if ! command -v agy >/dev/null 2>&1; then
        echo "[devcontainer:post-start] agy missing; retrying install..."
        tmp="$(mktemp -d)"
        if bash /workspaces/MiOS/.devcontainer/fetch-installer.sh \
             https://antigravity.google/cli/install.sh "${tmp}/install.sh" \
           && bash "${tmp}/install.sh" >/dev/null 2>&1; then
            echo "[devcontainer:post-start] agy installed: $(agy --version 2>/dev/null || echo unknown)"
        else
            echo "[devcontainer:post-start] agy still unreachable; will retry next start"
        fi
        rm -rf "${tmp}"
    fi

    # The credential keyring is a process, so it is gone after every restart and
    # agy re-asks for authentication without it. Best-effort, like the install above.
    DEVLOOP_ENV=/workspaces/-dev-loop/skills/dev-loop/scripts/env
    if [ -r "${DEVLOOP_ENV}/agy-keyring.sh" ]; then
        # shellcheck source=/dev/null
        . "${DEVLOOP_ENV}/agy-keyring.sh" || echo "[devcontainer:post-start] keyring not started; agy will ask to authenticate"
    fi

    # code-server once per start, loopback only, on [ports].code_server; its generated password stays in ~/.config/code-server.
    MIOS_TOML_GET=/workspaces/MiOS/usr/libexec/mios/mios-toml-get
    [ -f "$MIOS_TOML_GET" ] || MIOS_TOML_GET=/usr/libexec/mios/mios-toml-get
    cs_port="$(python3 "$MIOS_TOML_GET" ports code_server)"
    case "$cs_port" in
        ''|*[!0-9]*) echo "[devcontainer:post-start] ERROR: [ports].code_server did not resolve (got '${cs_port}')" >&2; exit 1 ;;
    esac
    if (exec 3<>"/dev/tcp/127.0.0.1/${cs_port}") 2>/dev/null; then
        echo "[devcontainer:post-start] code-server already listening on 127.0.0.1:${cs_port}"
    elif command -v code-server >/dev/null 2>&1; then
        cs_log="${XDG_STATE_HOME:-${HOME}/.local/state}/mios/code-server.log"
        mkdir -p "$(dirname "$cs_log")"
        setsid code-server --bind-addr "127.0.0.1:${cs_port}" >"$cs_log" 2>&1 </dev/null &
        echo "[devcontainer:post-start] code-server started on 127.0.0.1:${cs_port} (pid $!, log ${cs_log})"
    else
        echo "[devcontainer:post-start] ERROR: code-server is missing; the dev image bakes it, so rebuild the container" >&2
        exit 1
    fi

    # The verification gate must fail closed: a non-zero exit here fails
    # postStartCommand and surfaces in the devcontainer UI/CLI. Do not mask this
    # with `|| true` -- that turned every failing invariant into a silent pass.
    python3 harness/verification_gates.py --quick

    echo "[devcontainer:post-start] Ready for agent dispatch."
}

case "${1:-start}" in
    create)
        mios_create
        mios_platform
        ;;
    start)
        mios_start
        mios_post_start
        ;;
    platform)
        mios_platform
        ;;
    --help|-h)
        printf 'Usage: %s [create|start|platform]\n' "$0"
        ;;
    *)
        printf 'Unknown devcontainer lifecycle mode: %s\n' "$1" >&2
        exit 2
        ;;
esac
