#!/usr/bin/env bash
# Record the platform-specific contract without assuming unavailable privileges.
set -euo pipefail

if [[ -n "${CODESPACES:-}" ]]; then
    platform=codespaces
elif [[ "${CLOUD_SHELL:-}" == "true" ]]; then
    platform=google-cloud-shell
elif [[ -f /etc/oracle-release || -n "${OCI_CLI_CONFIG_FILE:-}" ]]; then
    platform=oracle-cloud-shell
else
    platform=generic-devcontainer
fi

config_dir="${HOME}/.config/mios"
install -d -m 0755 "${config_dir}"
cat > "${config_dir}/devcontainer.env" <<EOF
# Generated by MiOS Dev Container post-create.
MIOS_DEVELOPMENT_PLATFORM=${platform}
MIOS_ARTIFACT_PROFILE=portable
EOF

echo "[devcontainer:platform] ${platform}: portable MiOS development core configured."
echo "[devcontainer:platform] Use .devcontainer/artifact-builder on a trusted host for privileged disk artifacts."
