// AI-hint: PowerShell binding -- renders the export map and palette as a dot-sourceable module of $script:MIOS_* assignments.
// AI-related: automation/lib/globals.ps1
use toml::Value;

use crate::emit::build_exports_map;
use crate::palette::resolve as resolve_palette;

pub fn emit_powershell(merged: &Value, stack_offset: i32) -> String {
    let exports = build_exports_map(merged, stack_offset);
    let palette = resolve_palette(merged);

    let mut lines = Vec::new();
    lines.push("# Generated by mios-resolver --emit=powershell - DO NOT EDIT DIRECTLY".to_string());
    lines.push("# SSOT values derived from mios.toml layers".to_string());
    lines.push("".to_string());

    for (k, v) in &exports {
        let escaped = v.replace('\'', "''");
        lines.push(format!(
            "$script:{} = if ($env:{}) {{ $env:{} }} else {{ '{}' }}",
            k, k, k, escaped
        ));
    }

    for (k, v) in &palette {
        let key_name = format!("MIOS_COLOR_{}", k.to_uppercase());
        if !exports.contains_key(&key_name) {
            let escaped = v.replace('\'', "''");
            lines.push(format!(
                "$script:{} = if ($env:{}) {{ $env:{} }} else {{ '{}' }}",
                key_name, key_name, key_name, escaped
            ));
        }
    }

    lines.join("\n") + "\n"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_emit_powershell() {
        let val: Value = toml::from_str(r#"
[ports]
vllm = 8000
"#).unwrap();
        let ps = emit_powershell(&val, 0);
        assert!(ps.contains("$script:MIOS_PORT_VLLM = if ($env:MIOS_PORT_VLLM) { $env:MIOS_PORT_VLLM } else { '8000' }"));
    }
}
