// AI-hint: PowerShell binding -- renders the export map and palette as a dot-sourceable module of $script:MIOS_* assignments.
// AI-related: automation/lib/globals.ps1
use toml::Value;

use crate::emit::{build_exports_map, resolve_cross_references};
use crate::palette::resolve as resolve_palette;

pub fn emit_powershell(merged: &Value, stack_offset: i64) -> String {
    // Emitted as '...' below, and a PowerShell single-quoted string does not
    // interpolate either, so the same literal-export defect applies here.
    let mut exports = build_exports_map(merged, stack_offset);
    resolve_cross_references(&mut exports);
    let palette = resolve_palette(merged);

    let mut lines = Vec::new();
    lines.push("# Generated by mios-resolver --emit=powershell - DO NOT EDIT DIRECTLY".to_string());
    lines.push("# SSOT values derived from mios.toml layers".to_string());
    lines.push("".to_string());

    for (k, v) in &exports {
        let escaped = v.replace('\'', "''");
        lines.push(format!(
            "$script:{} = if ($env:{}) {{ $env:{} }} else {{ '{}' }}",
            k, k, k, escaped
        ));
    }

    for (k, v) in &palette {
        let key_name = format!("MIOS_COLOR_{}", k.to_uppercase());
        if !exports.contains_key(&key_name) {
            let escaped = v.replace('\'', "''");
            lines.push(format!(
                "$script:{} = if ($env:{}) {{ $env:{} }} else {{ '{}' }}",
                key_name, key_name, key_name, escaped
            ));
        }
    }

    lines.join("\n") + "\n"
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A PowerShell single-quoted string does not interpolate, so an
    /// unresolved ${MIOS_*} would be assigned as literal text.
    #[test]
    fn test_cross_reference_is_resolved_not_quoted_literal() {
        let val: Value = toml::from_str(
            r#"
[ports]
agent_pipe = 8700

[ai]
endpoint = "http://localhost:${MIOS_PORT_AGENT_PIPE}/v1"
"#,
        )
        .unwrap();
        let out = emit_powershell(&val, 0);
        assert!(
            out.contains("else { 'http://localhost:8700/v1' }"),
            "expected the resolved literal, got:\n{out}"
        );
        assert!(!out.contains("${MIOS_PORT_AGENT_PIPE}"));
    }

    #[test]
    fn test_emit_powershell() {
        let val: Value = toml::from_str(
            r#"
[ports]
vllm = 8000
"#,
        )
        .unwrap();
        let ps = emit_powershell(&val, 0);
        assert!(ps.contains("$script:MIOS_PORT_VLLM = if ($env:MIOS_PORT_VLLM) { $env:MIOS_PORT_VLLM } else { '8000' }"));
    }
}
