// AI-hint: Native projection of required dependency repositories from layered SSOT.
// AI-related: automation/06-enable-external-repos.sh, usr/share/mios/mios.toml [repos.external]
use toml::Value;

pub fn emit_repos(merged: &Value) -> Result<String, String> {
    let repos = merged
        .get("repos")
        .and_then(|v| v.get("external"))
        .and_then(Value::as_table)
        .ok_or("SSOT repos.external must be a table")?;
    let mut result = String::from("# Generated by native mios-resolver from layered mios.toml.\n");
    for (id, data) in repos {
        if id.is_empty()
            || !id
                .bytes()
                .all(|c| c.is_ascii_alphanumeric() || c == b'-' || c == b'_')
        {
            return Err("Invalid external repository identifier".into());
        }
        let enabled = data
            .get("enabled")
            .and_then(Value::as_bool)
            .ok_or_else(|| format!("repos.external.{id}.enabled must be a boolean"))?;
        if !enabled {
            continue;
        }
        let text = |key: &str| -> Result<&str, String> {
            data.get(key)
                .and_then(Value::as_str)
                .filter(|s| !s.is_empty() && !s.chars().any(char::is_control))
                .ok_or_else(|| format!("Invalid repos.external.{id}.{key}"))
        };
        let name = text("name")?;
        let baseurl = text("baseurl")?;
        let gpgkey = text("gpgkey")?;
        if !baseurl.starts_with("https://")
            || !gpgkey.starts_with("https://")
            || baseurl.contains(char::is_whitespace)
            || gpgkey.contains(char::is_whitespace)
        {
            return Err(format!(
                "repos.external.{id} requires HTTPS baseurl and gpgkey"
            ));
        }
        result.push_str(&format!("\n[mios-{id}]\nname={name}\nbaseurl={baseurl}\ngpgkey={gpgkey}\nenabled=1\ngpgcheck=1\nskip_if_unavailable=False\n"));
    }
    Ok(result)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn projects_operator_url_and_rejects_injected_ini_sections() {
        let mut data: Value = "[repos.external.hyprland]\nenabled=true\nname='Hyprland'\nbaseurl='https://example.test/fedora-$releasever-$basearch/'\ngpgkey='https://example.test/pubkey.gpg'".parse().unwrap();
        let output = emit_repos(&data).unwrap();
        assert!(output.contains("baseurl=https://example.test/fedora-$releasever-$basearch/"));
        assert!(output.contains("gpgcheck=1\nskip_if_unavailable=False"));
        data["repos"]["external"]["hyprland"]["name"] =
            Value::String("good\n[evil]\ngpgcheck=0".into());
        assert!(emit_repos(&data).is_err());
    }
    #[test]
    fn disabled_repo_is_omitted_and_insecure_enabled_repo_rejected() {
        let mut data: Value = "[repos.external.custom]\nenabled=false".parse().unwrap();
        assert!(!emit_repos(&data).unwrap().contains("[mios-custom]"));
        data["repos"]["external"]["custom"]["enabled"] = Value::Boolean(true);
        assert!(emit_repos(&data).is_err());
    }
}
