#!/usr/bin/env bash
# Install and launch the portable MiOS Dev Container from supported cloud shells.
set -euo pipefail

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
readonly LOCAL_PREFIX="${HOME}/.local"
readonly LOCAL_BIN="${LOCAL_PREFIX}/bin"
readonly SHELL_INIT="${LOCAL_PREFIX}/share/mios/cloud-shell-init.sh"

detect_platform() {
    if [[ "${CLOUD_SHELL:-}" == "true" ]]; then
        printf '%s\n' google-cloud-shell
    elif [[ -f /etc/oracle-release || -n "${OCI_CLI_CONFIG_FILE:-}" ]]; then
        printf '%s\n' oracle-cloud-shell
    else
        printf '%s\n' generic
    fi
}

install_cli() {
    if [[ -x "${LOCAL_BIN}/devcontainer" ]]; then
        return
    fi
    if ! command -v npm >/dev/null 2>&1; then
        echo "mios-cloud-shell: npm is required to install @devcontainers/cli" >&2
        exit 1
    fi
    echo "[mios-cloud-shell] Installing Dev Containers CLI under ${LOCAL_PREFIX}..."
    npm install --global --prefix "${LOCAL_PREFIX}" @devcontainers/cli
}

write_shell_init() {
    install -d -m 0755 "$(dirname "${SHELL_INIT}")"
    cat > "${SHELL_INIT}" <<'EOF'
# Generated by MiOS cloud-shell bootstrap.
export PATH="$HOME/.local/bin:$PATH"
alias mios-cloud-shell="$HOME/.local/share/mios/mios-cloud-shell-bootstrap"
EOF
    chmod 0644 "${SHELL_INIT}"

    local source_line='[ -f "$HOME/.local/share/mios/cloud-shell-init.sh" ] && . "$HOME/.local/share/mios/cloud-shell-init.sh"'
    if [[ ! -f "${HOME}/.bashrc" ]] || ! grep -Fqx "${source_line}" "${HOME}/.bashrc"; then
        printf '\n%s\n' "${source_line}" >> "${HOME}/.bashrc"
    fi
}

configure_oracle_podman() {
    [[ "$(detect_platform)" == oracle-cloud-shell ]] || return
    if ! command -v podman >/dev/null 2>&1; then
        echo "mios-cloud-shell: Oracle Cloud Shell did not provide podman" >&2
        exit 1
    fi

    local runtime_dir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
    local socket="${runtime_dir}/podman/podman.sock"
    if [[ ! -S "${socket}" ]]; then
        install -d -m 0700 "${runtime_dir}/podman"
        podman system service --time=0 "unix://${socket}" \
            >"${HOME}/.local/state/mios/podman-api.log" 2>&1 &
        for _ in $(seq 1 20); do
            [[ -S "${socket}" ]] && break
            sleep 1
        done
    fi
    if [[ ! -S "${socket}" ]]; then
        echo "mios-cloud-shell: Podman API socket did not start: ${socket}" >&2
        exit 1
    fi
    export DOCKER_HOST="unix://${socket}"
}

install_bootstrap() {
    install -d -m 0755 "${LOCAL_BIN}" "${LOCAL_PREFIX}/share/mios" "${HOME}/.local/state/mios"
    install -m 0755 "${SCRIPT_DIR}/bootstrap.sh" \
        "${LOCAL_PREFIX}/share/mios/mios-cloud-shell-bootstrap"
    install_cli
    write_shell_init
    echo "[mios-cloud-shell] $(detect_platform) bootstrap installed."
    echo "[mios-cloud-shell] Open a new shell, then run: mios-cloud-shell up"
}

launch_devcontainer() {
    install_cli
    configure_oracle_podman
    exec "${LOCAL_BIN}/devcontainer" up --workspace-folder "${ROOT}"
}

case "${1:-install}" in
    install)
        install_bootstrap
        ;;
    up)
        launch_devcontainer
        ;;
    *)
        echo "Usage: $0 [install|up]" >&2
        exit 2
        ;;
esac
