#!/usr/bin/bash
# enroll-mok.sh — 'MiOS' Secure Boot MOK enrollment helper.
#
# Uses mokutil throughout. sbctl is the WRONG tool for Fedora bootc
# (GRUB2+shim chain, not systemd-boot+UKI). See specs/SECUREBOOT.md.
#
# Variant-aware:
#   MiOS-2 (ucore-hci): prefers /etc/pki/akmods/certs/akmods-ublue.der (ublue key)
#                           if /etc/pki/mios/mok.der absent.
#
# Idempotent: exits 0 if key is already enrolled or pending enrollment.
#
# Usage:
#   enroll-mok.sh [--status] [--key /path/to/key.der]
#
# Exit codes:
#   0 = enrolled / pending / no-secureboot (no action needed)
#   1 = error
#   2 = key not found
#   3 = conflict (key CN matches but fingerprint differs — manual intervention)
set -euo pipefail

STATUS_ONLY=0
KEY_OVERRIDE=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --status)  STATUS_ONLY=1; shift ;;
        --key)     KEY_OVERRIDE="$2"; shift 2 ;;
        -*)        echo "Unknown option: $1" >&2; exit 1 ;;
        *)         break ;;
    esac
done

LOG_DIR=/var/log/mios
LOG_FILE="${LOG_DIR}/mok-enroll-$(date -u +%Y%m%dT%H%M%SZ).log"
install -d -m 0750 "$LOG_DIR"

log() {
    local msg="[mok-enroll] $*"
    echo "$msg"
    echo "$msg" >> "$LOG_FILE"
}

status_probe() {
    # Emit one of: enrolled | pending | not-enrolled | no-secureboot | conflict
    if ! command -v mokutil >/dev/null 2>&1; then
        echo "no-secureboot"
        return
    fi
    local sb_state
    sb_state=$(mokutil --sb-state 2>/dev/null || true)
    if echo "$sb_state" | grep -qi "SecureBoot disabled"; then
        echo "no-secureboot"
        return
    fi

    local key_path
    key_path=$(pick_key)
    if [[ -z "$key_path" ]]; then
        echo "not-enrolled"
        return
    fi

    local fingerprint
    fingerprint=$(openssl x509 -inform DER -in "$key_path" -fingerprint -sha256 -noout 2>/dev/null | sed 's/.*=//') || {
        echo "error"
        return
    }

    local enrolled_fps
    enrolled_fps=$(mokutil --list-enrolled 2>/dev/null | grep -i "SHA256 Fingerprint" | sed 's/.*: //' | tr -d ':' | tr '[:upper:]' '[:lower:]' || true)
    local pending_fps
    pending_fps=$(mokutil --list-new 2>/dev/null | grep -i "SHA256 Fingerprint" | sed 's/.*: //' | tr -d ':' | tr '[:upper:]' '[:lower:]' || true)
    local target_fp
    target_fp=$(echo "$fingerprint" | tr -d ':' | tr '[:upper:]' '[:lower:]')

    if echo "$enrolled_fps" | grep -qF "$target_fp"; then
        echo "enrolled"
    elif echo "$pending_fps" | grep -qF "$target_fp"; then
        echo "pending"
    else
        # Check if CN matches but fingerprint differs (key rotation conflict).
        local key_cn
        key_cn=$(openssl x509 -inform DER -in "$key_path" -subject -noout 2>/dev/null | sed 's/.*CN\s*=\s*//' | cut -d'/' -f1 || true)
        if [[ -n "$key_cn" ]]; then
            local enrolled_subjects
            enrolled_subjects=$(mokutil --list-enrolled 2>/dev/null || true)
            if echo "$enrolled_subjects" | grep -qF "$key_cn"; then
                echo "conflict"
                return
            fi
        fi
        echo "not-enrolled"
    fi
}

pick_key() {
    if [[ -n "$KEY_OVERRIDE" ]]; then
        echo "$KEY_OVERRIDE"
        return
    fi
    # MiOS-specific key (generated by generate-mok-key.sh)
    [[ -f /etc/pki/mios/mok.der ]] && { echo /etc/pki/mios/mok.der; return; }
    # MiOS-2 (ucore-hci): ublue pre-signed NVIDIA kmods key
    [[ -f /etc/pki/akmods/certs/akmods-ublue.der ]] && { echo /etc/pki/akmods/certs/akmods-ublue.der; return; }
    echo ""
}

# ── status probe mode ─────────────────────────────────────────────────────────

if (( STATUS_ONLY == 1 )); then
    status_probe
    exit 0
fi

# ── runtime checks ────────────────────────────────────────────────────────────

log "=== 'MiOS' MOK Enrollment ==="

if ! command -v mokutil >/dev/null 2>&1; then
    log "mokutil not found — install it: sudo dnf install mokutil"
    exit 1
fi

# Secure Boot state check
sb_state=$(mokutil --sb-state 2>/dev/null || true)
if echo "$sb_state" | grep -qi "SecureBoot disabled"; then
    log "Secure Boot is disabled — MOK enrollment not required"
    exit 0
fi
log "Secure Boot state: $sb_state"

# Pick key
KEY=$(pick_key)
if [[ -z "$KEY" ]]; then
    log "No MOK key found. Generate one with:"
    log "  sudo automation/generate-mok-key.sh"
    exit 2
fi
log "Using key: $KEY"

FINGERPRINT=$(openssl x509 -inform DER -in "$KEY" -fingerprint -sha256 -noout | sed 's/.*=//') || {
    log "Cannot read key fingerprint from $KEY"
    exit 1
}
log "Key fingerprint: $FINGERPRINT"

# Idempotency check
CURRENT_STATUS=$(status_probe)
log "Current status: $CURRENT_STATUS"

case "$CURRENT_STATUS" in
    enrolled)
        log "Key already enrolled — no action needed"
        exit 0
        ;;
    pending)
        log "Key already queued for enrollment — reboot to complete in MokManager"
        exit 0
        ;;
    conflict)
        log "ERROR: A key with the same CN is already enrolled but with a different fingerprint."
        log "This indicates a key rotation. Manual steps required:"
        log "  1. mokutil --delete /etc/pki/mios/mok.old.der  (previous key)"
        log "  2. Reboot and complete deletion in MokManager"
        log "  3. Re-run this script"
        exit 3
        ;;
    no-secureboot)
        log "Secure Boot appears disabled — nothing to enroll"
        exit 0
        ;;
esac

# ── enroll ────────────────────────────────────────────────────────────────────

log "Queuing $KEY for MOK enrollment (using --root-pw)"
log ""
log "You will be prompted to confirm using the system root password."
log "On next reboot, MokManager will ask for this same password."
log ""

# --root-pw binds the enrollment to the current root password hash in /etc/shadow.
# This avoids shipping a hardcoded secret (unlike ublue's 'universalblue' default).
if ! mokutil --import "$KEY" --root-pw; then
    log "mokutil --import failed"
    # Attempt rollback
    log "Attempting to revoke pending import (rollback)..."
    mokutil --revoke-import "$KEY" 2>/dev/null || log "revoke-import also failed — check mokutil state manually"
    exit 1
fi

# Optional: set MokManager timeout (non-fatal — known to fail on some ASUS boards)
mokutil --timeout 10 2>/dev/null || log "note: --timeout ignored on this firmware (non-fatal)"

log ""
log "✓ Key queued for enrollment."
log ""
log "NEXT STEPS:"
log "  1. Reboot the system."
log "  2. In MokManager, choose 'Enroll MOK' and enter the root password."
log "  3. Reboot again. The key will be active."
log ""
log "── TPM2 WARNING ────────────────────────────────────────────────────────────"
log "If you have LUKS volumes sealed to TPM2 PCR 7 (systemd-cryptenroll),"
log "every MOK mutation changes PCR 7 and WILL break automatic unlock."
log "After this reboot completes enrollment, re-seal with:"
log "  systemd-cryptenroll --wipe-slot=tpm2 /dev/DISK"
log "  systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7+14 /dev/DISK"
log "────────────────────────────────────────────────────────────────────────────"
log ""
log "Full log: $LOG_FILE"
