#!/usr/bin/env python3
# AI-hint: GENERATES usr/share/doc/mios/reference/mini-vs-hosted.md -- the systematic, surface-by-surface comparison of a MiOS-Mini seat against a fully hosted, feature-complete MiOS blade. Every number is DERIVED from mios.toml ([blade.archetypes], [blade.requires], [blade].seat_side, [greenboot], [urls]), because a hand-written comparison is exactly the document that goes stale the moment an archetype gains a capability. --check is the drift gate.
# AI-related: usr/share/mios/mios.toml, usr/share/doc/mios/adr/0016-blade-node-topology.md, automation/98-drift-checks.sh, tools/test_generate-mini-vs-hosted.py
# AI-functions: load, archetype_rows, seat_units, gated_off_on_seat, greenboot_rows, overlay_keys, render, main
"""Project the seat-vs-blade comparison out of the SSOT."""

import os
import sys

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover -- py<3.11
    import tomli as tomllib  # type: ignore

TOML = "usr/share/mios/mios.toml"
OUT = "usr/share/doc/mios/reference/mini-vs-hosted.md"
SEAT = "endpoint"


def load(root: str) -> dict:
    with open(os.path.join(root, TOML), "rb") as fh:
        return tomllib.load(fh)


def _caps(v):
    return [v] if isinstance(v, str) else list(v or [])


def _requires(data: dict) -> dict:
    return {k: _caps(v) for k, v in
            ((data.get("blade") or {}).get("requires") or {}).items()}


def archetype_rows(data: dict) -> list:
    """(archetype, capabilities, gated units started, total units)."""
    blade = data.get("blade") or {}
    arche = blade.get("archetypes") or {}
    req = _requires(data)
    seat_n = len(blade.get("seat_side") or [])
    rows = []
    for name in sorted(arche):
        have = set(_caps(arche[name]))
        started = sum(1 for caps in req.values() if set(caps) <= have)
        rows.append((name, sorted(have), started, started + seat_n))
    return rows


def seat_units(data: dict) -> list:
    return sorted((data.get("blade") or {}).get("seat_side") or [])


def gated_off_on_seat(data: dict) -> list:
    """Every unit a seat does NOT start, with the capability that withholds it."""
    have = set(_caps(((data.get("blade") or {}).get("archetypes") or {}).get(SEAT)))
    out = []
    for unit, caps in sorted(_requires(data).items()):
        missing = sorted(set(caps) - have)
        if missing:
            out.append((unit, missing))
    return out


def greenboot_rows(data: dict) -> list:
    """(service, unit it probes, whether a seat probes it)."""
    gb = data.get("greenboot") or {}
    probe = gb.get("probe") or {}
    req = _requires(data)
    have = set(_caps(((data.get("blade") or {}).get("archetypes") or {}).get(SEAT)))
    seat = set(seat_units(data))
    rows = []
    for svc in gb.get("critical_services") or []:
        spec = probe.get(str(svc).replace("-", "_")) or probe.get(svc) or {}
        unit = str(spec.get("unit") or ("mios-%s.service" % svc))
        stem = unit[:-len(".service")] if unit.endswith(".service") else unit
        caps = req.get(stem) or req.get("mios-%s" % svc) or []
        probed = stem in seat or "mios-%s" % svc in seat or set(caps) <= have
        rows.append((str(svc), unit, bool(probed), sorted(caps)))
    return rows


def overlay_keys(data: dict) -> list:
    """The canonical keys a seat's /etc/mios overlay repoints -- the key each
    service's consumers already resolve, never a second name for it."""
    return [
        ("[ai].endpoint", "MIOS_AI_ENDPOINT", "the AI front door every client dials"),
        ("[search].endpoint", "MIOS_SEARCH_ENDPOINT", "web search"),
        ("[nodes.<name>].endpoint", "-", "a compute lane in the fan-out pool"),
        ("[blades.<name>]", "-", "a remote machine's capacity envelope"),
        ("[urls].<tile>", "MIOS_URLS_<TILE>", "a browser-openable tile only"),
    ]


def render(data: dict) -> str:
    rows = archetype_rows(data)
    seat_row = next(r for r in rows if r[0] == SEAT)
    full = max(rows, key=lambda r: r[3])
    gated = gated_off_on_seat(data)
    gb = greenboot_rows(data)
    blade = data.get("blade") or {}

    L = []
    a = L.append
    a("<!-- AI-hint: GENERATED by tools/generate-mini-vs-hosted.py from mios.toml. "
      "DO NOT EDIT -- re-run the generator. The surface-by-surface difference "
      "between a MiOS-Mini seat and a fully hosted MiOS blade, with every count "
      "derived from [blade.archetypes]/[blade.requires]/[blade].seat_side so the "
      "comparison cannot go stale. -->")
    a("<!-- AI-related: usr/share/mios/mios.toml, usr/share/doc/mios/adr/"
      "0016-blade-node-topology.md, tools/generate-mini-vs-hosted.py -->")
    a("")
    a("# MiOS-Mini vs a fully hosted MiOS — what actually differs")
    a("")
    a("**\"MiOS-Mini\" names a `[blade].type`, never an artifact** (ADR-0016 D9). "
      "There is no MiOS-Mini Containerfile, no MiOS-Mini tag, and no conditional "
      "bake — the seat and the blade are the same OCI image, byte for byte. A "
      "seat is `[blade].type = \"%s\"`, an archetype that grants no "
      "capabilities, plus an `/etc/mios` overlay. Every difference below is a "
      "*runtime* difference." % SEAT)
    a("")
    a("| Surface | MiOS-Mini (seat) | Fully hosted (`%s`) |" % full[0])
    a("|---|---|---|")
    a("| Image | identical OCI image and tag | identical |")
    a("| Bake | every payload baked, including model weights | identical |")
    a("| Units started | **%d** | **%d** |" % (seat_row[3], full[3]))
    a("| Capabilities granted | *(none)* | `%s` |" % "`, `".join(full[1]))
    a("| Capability-gated units it starts | %d | %d |" % (seat_row[2], full[2]))
    a("| Always-on units (`[blade].seat_side`) | %d | %d |"
      % (len(seat_units(data)), len(seat_units(data))))
    a("| Local inference lanes | **0** | up to %d |"
      % sum(1 for u, _ in gated if "llm" in u or u.endswith("cpu-node")))
    a("| Greenboot probes | %d of %d critical services | %d of %d |"
      % (sum(1 for r in gb if r[2]), len(gb),
         len(gb), len(gb)))
    a("| Addressing | `/etc/mios` overlay repoints the canonical keys | vendor defaults, all `localhost` |")
    a("")
    a("## What a seat runs, and why each one")
    a("")
    a("`[blade].seat_side` is a positive declaration, not debt: a seat runs what "
      "the **person** touches, a blade runs what the **work** needs.")
    a("")
    a("| Unit | Why a seat keeps it |")
    a("|---|---|")
    for u in seat_units(data):
        a("| `%s` | local I/O |" % u)
    a("")
    a("## What a seat does not run")
    a("")
    a("%d units are capability-gated off. A failed `ConditionPathExists` is a "
      "clean skip, not a failure — the unit is *baked and present*, it simply "
      "never starts." % len(gated))
    a("")
    a("| Withheld capability | Units it gates off |")
    a("|---|---|")
    by_cap = {}
    for unit, missing in gated:
        by_cap.setdefault(", ".join(missing), []).append(unit)
    for cap in sorted(by_cap):
        a("| `%s` | %d |" % (cap, len(by_cap[cap])))
    a("")
    a("## Health: what greenboot asks on each")
    a("")
    a("| Critical service | Unit probed | On a seat |")
    a("|---|---|---|")
    for svc, unit, probed, caps in gb:
        a("| `%s` | `%s` | %s |"
          % (svc, unit, "probed" if probed else
             "skipped (needs `%s`)" % "`, `".join(caps)))
    a("")
    a("`[greenboot].blade_reachability_critical = %s` — a seat whose blade is "
      "unreachable does **not** roll itself back."
      % str(bool((data.get("greenboot") or {}).get("blade_reachability_critical"))).lower())
    a("")
    a("## Addressing: the only thing an operator changes")
    a("")
    a("A service's canonical address is the key its consumers already resolve "
      "(ADR-0016 Decision 1). \"local, localhost or remote\" are three *values* "
      "of one mechanism.")
    a("")
    a("| Overlay key | Canonical env | What it moves |")
    a("|---|---|---|")
    for key, env, what in overlay_keys(data):
        a("| `%s` | `%s` | %s |" % (key, env, what))
    a("")
    a("## The seat's defining constraint")
    a("")
    a("A seat has **no local inference floor**. Every lane — heavy, alt, light "
      "and the CPU node — is capability-gated off, including the lane the "
      "resolver calls \"the always-on floor\". When the blade is unreachable a "
      "seat has a front door that can reach nothing. The model weights are "
      "baked regardless (Law 12), so a seat carries them and never loads them.")
    a("")
    a("Whether that is right is an operator decision, recorded in ADR-0016 "
      "Decision 6, not a defect: giving a seat a micro local lane would trade "
      "\"offload *all* services\" for a degraded-but-alive floor.")
    a("")
    return "\n".join(L) + "\n"


def main() -> int:
    root = os.environ.get("MIOS_DRIFT_ROOT") or os.environ.get("MIOS_ROOT") or "."
    check = "--check" in sys.argv
    try:
        data = load(root)
    except OSError as exc:
        print("generate-mini-vs-hosted: cannot read the SSOT: %s" % exc,
              file=sys.stderr)
        return 1
    want = render(data)
    path = os.path.join(root, OUT)
    if check:
        try:
            with open(path, encoding="utf-8") as fh:
                have = fh.read()
        except OSError:
            print("generate-mini-vs-hosted: %s is missing -- run the generator"
                  % OUT, file=sys.stderr)
            return 1
        if have.replace("\r\n", "\n") != want:
            print("generate-mini-vs-hosted: %s has drifted from the SSOT -- "
                  "re-run tools/generate-mini-vs-hosted.py" % OUT, file=sys.stderr)
            return 1
        print("[generate-mini-vs-hosted] %s matches the SSOT" % OUT)
        return 0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(want)
    print("[generate-mini-vs-hosted] wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
