#!/bin/bash
# rtx4090-vfio-configurator.sh
# Automated RTX 4090 VFIO isolation for 'MiOS' (Fedora bootc)
# Part of MiOS-Build virtualization host setup

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   exit 1
fi

# Configuration variables
VFIO_CONF="/etc/modprobe.d/vfio.conf"
BACKUP_SUFFIX=".backup-$(date +%Y%m%d-%H%M%S)"

# Step 1: Detect RTX 4090
log_info "Detecting NVIDIA RTX 4090..."

# Find RTX 4090 by device name
RTX4090_INFO=$(lspci -nn | grep -i "RTX 4090" | head -n1)

if [[ -z "$RTX4090_INFO" ]]; then
    log_error "RTX 4090 not detected. Exiting."
    exit 1
fi

log_success "Found: $RTX4090_INFO"

# Extract PCI address and IDs
PCI_ADDRESS=$(echo "$RTX4090_INFO" | awk '{print $1}')
GPU_ID=$(echo "$RTX4090_INFO" | grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}(?=\])' | head -n1)

log_info "PCI Address: $PCI_ADDRESS"
log_info "GPU ID: $GPU_ID"

# Find associated audio controller
AUDIO_INFO=$(lspci -nn -s "${PCI_ADDRESS%%:*}:" | grep -i "audio" | grep -i "nvidia")
AUDIO_ID=$(echo "$AUDIO_INFO" | grep -oP '\[\K[0-9a-f]{4}:[0-9a-f]{4}(?=\])' | head -n1)

if [[ -z "$AUDIO_ID" ]]; then
    log_warning "Audio controller not found. Proceeding with GPU only."
    VFIO_IDS="$GPU_ID"
else
    log_success "Found audio controller: $AUDIO_ID"
    VFIO_IDS="$GPU_ID,$AUDIO_ID"
fi

# Step 2: Check IOMMU support
log_info "Checking IOMMU support..."

CPU_VENDOR=$(lscpu | grep "Vendor ID" | awk '{print $3}')

case "$CPU_VENDOR" in
    AuthenticAMD)
        IOMMU_PARAM="amd_iommu=on"
        IOMMU_CHECK=$(dmesg | grep -i "AMD-Vi")
        ;;
    GenuineIntel)
        IOMMU_PARAM="intel_iommu=on"
        IOMMU_CHECK=$(dmesg | grep -i "Intel-VT")
        ;;
    *)
        log_error "Unknown CPU vendor: $CPU_VENDOR"
        exit 1
        ;;
esac

if [[ -z "$IOMMU_CHECK" ]]; then
    log_warning "IOMMU not detected in dmesg. Make sure it's enabled in BIOS/UEFI."
else
    log_success "IOMMU support detected for $CPU_VENDOR CPU"
fi

# Step 3: Check IOMMU group isolation
log_info "Checking IOMMU group for RTX 4090..."

IOMMU_GROUP=$(basename $(readlink /sys/bus/pci/devices/0000:$PCI_ADDRESS/iommu_group) 2>/dev/null || echo "unknown")
IOMMU_GROUP_DEVICES=$(ls -1 /sys/bus/pci/devices/0000:$PCI_ADDRESS/iommu_group/devices 2>/dev/null | wc -l)

log_info "IOMMU Group: $IOMMU_GROUP"
log_info "Devices in group: $IOMMU_GROUP_DEVICES"

if [[ "$IOMMU_GROUP_DEVICES" -gt 3 ]]; then
    log_warning "IOMMU group contains $IOMMU_GROUP_DEVICES devices. Consider ACS override patch if isolation is poor."
fi

# Step 4: Create VFIO modprobe configuration
log_info "Creating VFIO modprobe configuration..."

if [[ -f "$VFIO_CONF" ]]; then
    cp "$VFIO_CONF" "${VFIO_CONF}${BACKUP_SUFFIX}"
    log_info "Backed up existing config to ${VFIO_CONF}${BACKUP_SUFFIX}"
fi

cat > "$VFIO_CONF" << EOF
# VFIO configuration for RTX 4090
# Generated by rtx4090-vfio-configurator.sh on $(date)

# Bind RTX 4090 to VFIO-PCI driver
options vfio-pci ids=$VFIO_IDS

# Ensure VFIO loads before graphics drivers
softdep nvidia pre: vfio-pci
softdep nouveau pre: vfio-pci
softdep amdgpu pre: vfio-pci
softdep radeon pre: vfio-pci

# Optional: Disable NVIDIA drivers entirely if only using for passthrough
# Uncomment below if you want to blacklist nvidia drivers
# blacklist nvidia
# blacklist nvidia_drm
# blacklist nvidia_modeset
# blacklist nouveau
EOF

log_success "Created $VFIO_CONF"

# Step 5: Update bootc kernel arguments
log_info "Applying kernel parameters via bootc..."
KERNEL_PARAMS="$IOMMU_PARAM iommu=pt vfio-pci.ids=$VFIO_IDS"
log_info "Applying: $KERNEL_PARAMS"

# bootc kargs edit stages the arguments for the next boot natively
bootc kargs edit --append-if-missing="$IOMMU_PARAM" \
                 --append-if-missing="iommu=pt" \
                 --append-if-missing="vfio-pci.ids=$VFIO_IDS"

log_success "bootc kargs updated. Changes will take effect on next reboot."

# Step 6: Create IOMMU group viewer script
IOMMU_SCRIPT="/usr/local/bin/iommu-groups"

if [[ ! -f "$IOMMU_SCRIPT" ]]; then
    log_info "Creating IOMMU group viewer script..."

    cat > "$IOMMU_SCRIPT" << 'EOF'
#!/bin/bash
shopt -s nullglob
for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
    echo "IOMMU Group ${g##*/}:"
    for d in $g/devices/*; do
        echo -e "\t$(lspci -nns ${d##*/})"
    done;
done;
EOF

    chmod +x "$IOMMU_SCRIPT"
    log_success "Created $IOMMU_SCRIPT"
fi

# Step 7: Summary and next steps
echo ""
log_success "RTX 4090 VFIO configuration complete!"
echo ""
echo -e "${BLUE}â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*${NC}"
echo -e "${GREEN}Configuration Summary:${NC}"
echo -e "${BLUE}â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*${NC}"
echo ""
echo "GPU Device IDs:        $VFIO_IDS"
echo "IOMMU Group:           $IOMMU_GROUP ($IOMMU_GROUP_DEVICES devices)"
echo ""
echo -e "${BLUE}â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*${NC}"
echo -e "${YELLOW}Next Steps:${NC}"
echo -e "${BLUE}â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*${NC}"
echo ""
echo "1. Reboot the system"
echo ""
echo "2. After reboot, verify VFIO binding:"
echo "   $ lspci -nnk -d $GPU_ID"
echo "   $ ls -la /dev/vfio/"
echo ""
echo "3. View IOMMU groups:"
echo "   $ iommu-groups"
echo ""
echo "4. Check kernel messages:"
echo "   $ dmesg | grep -i vfio"
echo "   $ dmesg | grep $GPU_ID"
echo ""
echo -e "${BLUE}â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*${NC}"
echo -e "${YELLOW}Rollback Instructions:${NC}"
echo -e "${BLUE}â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*${NC}"
echo ""
echo "If you need to revert changes:"
echo "  sudo bootc kargs edit --delete vfio-pci.ids=$VFIO_IDS --delete iommu=pt"
echo "  sudo rm -f $VFIO_CONF"
echo "  sudo reboot"
echo ""
echo -e "${BLUE}â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*â*${NC}"
echo ""

read -p "Reboot now? (y/N): " REBOOT_NOW

if [[ "$REBOOT_NOW" =~ ^[Yy]$ ]]; then
    log_info "Rebooting system..."
    systemctl reboot
else
    log_warning "Remember to reboot before testing VFIO passthrough!"
fi
