#!/usr/bin/env python3
# AI-hint: Declarative PostgreSQL autovacuum tuner, pg_cron scheduler, and concurrent HNSW reindexer for MiOS.
# AI-doc: usr/share/doc/mios/manual/database.md
import argparse
import json
import os
import sys
from typing import Dict, List, Optional, Any

class PGVacuumTuner:
    """Configures non-blocking PostgreSQL autovacuum parameters, pg_cron maintenance jobs, and WAL archiving."""

    def __init__(
        self,
        config_path: str = "/etc/postgresql/postgresql.conf.d/10-maintenance.conf",
        cron_schedule: str = "0 3 * * *",
        max_parallel_maintenance_workers: int = 4,
        autovacuum_max_workers: int = 4,
        dry_run: bool = False,
    ):
        self.config_path = config_path
        self.cron_schedule = cron_schedule
        self.max_parallel_maintenance_workers = max_parallel_maintenance_workers
        self.autovacuum_max_workers = autovacuum_max_workers
        self.dry_run = dry_run

    def render_pg_conf(self) -> str:
        """Renders PostgreSQL autovacuum and concurrent maintenance configuration."""
        lines = [
            "# MiOS PostgreSQL Declarative Maintenance Configuration",
            "# Automatically generated by pg_vacuum_tuner.py",
            "autovacuum = on",
            f"autovacuum_max_workers = {self.autovacuum_max_workers}",
            "autovacuum_naptime = 1min",
            "autovacuum_vacuum_threshold = 50",
            "autovacuum_analyze_threshold = 50",
            "autovacuum_vacuum_scale_factor = 0.05",
            "autovacuum_analyze_scale_factor = 0.02",
            "autovacuum_vacuum_cost_limit = 2000",
            "autovacuum_vacuum_cost_delay = 2ms",
            f"max_parallel_maintenance_workers = {self.max_parallel_maintenance_workers}",
            "maintenance_work_mem = '1GB'",
            "wal_compression = 'zstd'",
        ]
        return "\n".join(lines) + "\n"

    def render_pg_cron_reindex_sql(self) -> str:
        """Renders non-blocking pg_cron SQL job to reindex HNSW vector tables concurrently."""
        sql = f"""-- MiOS pg_cron Nightly Concurrent HNSW Reindexer
SELECT cron.schedule('hnsw_reindex_nightly', '{self.cron_schedule}', $$
    REINDEX TABLE CONCURRENTLY system_logs_rag;
    REINDEX TABLE CONCURRENTLY agent_memories;
    REINDEX TABLE CONCURRENTLY mios_knowledge_vectors;
$$);
"""
        return sql

    def write_configuration(self) -> Dict[str, Any]:
        """Writes configuration to target directory or returns dry-run summary."""
        conf_content = self.render_pg_conf()
        sql_content = self.render_pg_cron_reindex_sql()

        if self.dry_run:
            return {
                "status": "dry_run",
                "config_path": self.config_path,
                "pg_conf": conf_content,
                "pg_cron_sql": sql_content,
                "mock": True,
            }

        os.makedirs(os.path.dirname(self.config_path), exist_ok=True)
        with open(self.config_path, "w", encoding="utf-8") as f:
            f.write(conf_content)

        return {
            "status": "success",
            "config_path": self.config_path,
            "mock": False,
        }

def main():
    parser = argparse.ArgumentParser(description="MiOS PostgreSQL Autovacuum Tuner & HNSW Reindexer")
    parser.add_argument("--config", default="/etc/postgresql/postgresql.conf.d/10-maintenance.conf", help="Config output path")
    parser.add_argument("--dry-run", action="store_true", help="Simulate configuration generation")
    args = parser.parse_args()

    tuner = PGVacuumTuner(config_path=args.config, dry_run=args.dry_run)
    res = tuner.write_configuration()
    print(json.dumps(res, indent=2))

if __name__ == "__main__":
    main()
