#!/usr/bin/env python3
# AI-hint: Automated kernel fuzz crash deduplication engine and PostgreSQL bug_tracker logger.
# AI-related: usr/libexec/mios/kernel/crash_dedupe.py, tests/test-crash-dedupe.py, usr/share/mios/postgres/schema-init.sql
"""Automated Fuzz Crash Deduplication & Bug Logger (T-558).

Triages raw serial and Syzkaller execution logs, isolates KASAN backtraces,
computes normalized callstack fingerprints (stripping runtime offsets),
extracts C/Syz reproducers, and manages bug tracking records in PostgreSQL.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass, field
import hashlib
import json
import logging
import os
import re
import sys
import time
from typing import Any, Dict, List, Optional, Tuple

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("mios-crash-dedupe")

# Regex to strip dynamic offsets, timestamps, and memory pointers
TIMESTAMP_REGEX = re.compile(r"\[\s*\d+\.\d+\]\s*")
ADDR_OFFSET_REGEX = re.compile(r"\+0x[0-9a-fA-F]+(?:/0x[0-9a-fA-F]+)?|\+[0-9a-fA-F]+(?:/[0-9a-fA-F]+)?")
ADDR_HEX_REGEX = re.compile(r"\[<[0-9a-fA-F]+>\]|\b0x[0-9a-fA-F]+\b")


@dataclass
class CrashReport:
    """Structured and deduplicated kernel crash report."""
    crash_hash: str
    title: str
    subsystem: str
    fault_type: str
    stack_frames: List[str]
    c_reproducer: Optional[str] = None
    syz_reproducer: Optional[str] = None
    raw_log: str = ""
    occurrences: int = 1
    status: str = "open"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class CrashTriageEngine:
    """Engine parsing kernel crashes, computing stack hashes, and logging to bug_tracker."""

    def __init__(self, mock: bool = False) -> None:
        self.mock = mock
        self._mock_db: Dict[str, CrashReport] = {}
        if self.mock:
            self._init_mock_state()

    def _init_mock_state(self) -> None:
        """Seeds initial mock database records."""
        report = CrashReport(
            crash_hash="a9f2e3b14c5d6e78",
            title="KASAN: use-after-free in bpf_prog_put",
            subsystem="bpf",
            fault_type="use-after-free",
            stack_frames=["bpf_prog_put", "bpf_prog_release", "__fput", "ksys_close", "do_syscall_64"],
            c_reproducer="// autogenerated by syzkaller\n#include <linux/bpf.h>\nint main() { ... }",
            syz_reproducer="bpf$BPF_PROG_LOAD(0x1, &(0x7f0000)=..., 0x80)",
            occurrences=3,
            status="open",
        )
        self._mock_db[report.crash_hash] = report

    def normalize_frame(self, frame_line: str) -> str:
        """Strips dynamic hexadecimal addresses, register numbers, and offsets from stack frame line."""
        cleaned = TIMESTAMP_REGEX.sub("", frame_line)
        cleaned = re.sub(r"^\s*(\?|\s)*", "", cleaned)  # remove leading ?
        cleaned = ADDR_OFFSET_REGEX.sub("", cleaned)
        cleaned = ADDR_HEX_REGEX.sub("", cleaned)
        # Extract first valid C symbol token
        match = re.search(r"([a-zA-Z_][a-zA-Z0-9_]*)", cleaned)
        if match:
            return match.group(1).strip()
        return cleaned.strip()

    def compute_stack_hash(self, frames: List[str]) -> str:
        """Generates normalized SHA-256 fingerprint from cleaned callstack function symbols."""
        norm_frames = [self.normalize_frame(f) for f in frames if f.strip()]
        # Take up to top 8 normalized function names
        sig_text = "\n".join(norm_frames[:8])
        return hashlib.sha256(sig_text.encode("utf-8")).hexdigest()[:16]

    def extract_reproducers(self, log_text: str) -> Tuple[Optional[str], Optional[str]]:
        """Extracts C and Syzkaller reproducer snippets embedded in log."""
        c_rep: Optional[str] = None
        syz_rep: Optional[str] = None

        # Detect C reproducer
        c_match = re.search(r"(#define _GNU_SOURCE.*?int main\(.*?\n\})", log_text, re.DOTALL)
        if c_match:
            c_rep = c_match.group(1).strip()

        # Detect Syz reproducer
        syz_match = re.search(r"#\s*syz-reproducer:\s*\n((?:[a-zA-Z0-9_$]+\(.*\)\n)+)", log_text)
        if syz_match:
            syz_rep = syz_match.group(1).strip()

        return c_rep, syz_rep

    def parse_log(self, log_text: str) -> List[CrashReport]:
        """Triages log text into structured crash reports."""
        reports: List[CrashReport] = []
        lines = log_text.splitlines()

        i = 0
        while i < len(lines):
            line = lines[i]
            # Check for KASAN / OOPS / Panic header
            if "BUG: KASAN:" in line or "BUG: unable to handle" in line or "Kernel panic" in line:
                title = line.strip()
                fault_type = "unknown"
                if "use-after-free" in line:
                    fault_type = "use-after-free"
                elif "out-of-bounds" in line:
                    fault_type = "slab-out-of-bounds"
                elif "null" in line.lower() or "unable to handle" in line.lower():
                    fault_type = "null-ptr-deref"
                elif "panic" in line.lower():
                    fault_type = "kernel-panic"

                # Subsystem classification
                subsystem = "core"
                if "bpf" in line.lower():
                    subsystem = "bpf"
                elif "virtio" in line.lower():
                    subsystem = "virtiofs"
                elif "blk" in line.lower() or "nvme" in line.lower() or "scsi" in line.lower():
                    subsystem = "storage"
                elif "net" in line.lower() or "tcp" in line.lower():
                    subsystem = "net"

                # Collect Call Trace
                stack_frames = []
                j = i + 1
                in_trace = False
                while j < len(lines):
                    sub_line = lines[j]
                    if "Call Trace:" in sub_line:
                        in_trace = True
                        j += 1
                        continue
                    if in_trace:
                        if sub_line.startswith("===") or "BUG:" in sub_line or "Kernel panic" in sub_line or not sub_line.strip():
                            break
                        norm = self.normalize_frame(sub_line)
                        if norm:
                            stack_frames.append(norm)
                    j += 1

                if not stack_frames:
                    stack_frames = [self.normalize_frame(title)]

                crash_hash = self.compute_stack_hash(stack_frames)
                c_rep, syz_rep = self.extract_reproducers(log_text)

                report = CrashReport(
                    crash_hash=crash_hash,
                    title=title,
                    subsystem=subsystem,
                    fault_type=fault_type,
                    stack_frames=stack_frames,
                    c_reproducer=c_rep,
                    syz_reproducer=syz_rep,
                    raw_log=line,
                )
                reports.append(report)
                i = j
            else:
                i += 1

        return reports

    def record_to_db(self, report: CrashReport, db_url: Optional[str] = None) -> Dict[str, Any]:
        """Inserts or updates crash record in bug_tracker database table."""
        if self.mock or not db_url:
            if report.crash_hash in self._mock_db:
                existing = self._mock_db[report.crash_hash]
                existing.occurrences += 1
                return {
                    "status": "updated",
                    "action": "increment_occurrence",
                    "crash_hash": report.crash_hash,
                    "occurrences": existing.occurrences,
                    "title": existing.title,
                }
            else:
                self._mock_db[report.crash_hash] = report
                return {
                    "status": "inserted",
                    "action": "new_bug_created",
                    "crash_hash": report.crash_hash,
                    "occurrences": 1,
                    "title": report.title,
                }

        # PostgreSQL real execution
        import psycopg2  # type: ignore
        conn = psycopg2.connect(db_url)
        try:
            with conn.cursor() as cur:
                # Ensure table exists
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS bug_tracker (
                        id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                        crash_hash text NOT NULL UNIQUE,
                        title text NOT NULL,
                        subsystem text NOT NULL,
                        fault_type text NOT NULL,
                        stack_frames jsonb NOT NULL,
                        c_reproducer text,
                        syz_reproducer text,
                        occurrences integer DEFAULT 1,
                        first_seen timestamptz DEFAULT now(),
                        last_seen timestamptz DEFAULT now(),
                        status text DEFAULT 'open'
                    );
                """)
                cur.execute("""
                    INSERT INTO bug_tracker (
                        crash_hash, title, subsystem, fault_type, stack_frames, c_reproducer, syz_reproducer, occurrences
                    ) VALUES (%s, %s, %s, %s, %s, %s, %s, 1)
                    ON CONFLICT (crash_hash) DO UPDATE SET
                        occurrences = bug_tracker.occurrences + 1,
                        last_seen = now(),
                        c_reproducer = COALESCE(EXCLUDED.c_reproducer, bug_tracker.c_reproducer),
                        syz_reproducer = COALESCE(EXCLUDED.syz_reproducer, bug_tracker.syz_reproducer)
                    RETURNING occurrences;
                """, (
                    report.crash_hash,
                    report.title,
                    report.subsystem,
                    report.fault_type,
                    json.dumps(report.stack_frames),
                    report.c_reproducer,
                    report.syz_reproducer,
                ))
                occ = cur.fetchone()[0]
                conn.commit()
                return {
                    "status": "success",
                    "crash_hash": report.crash_hash,
                    "occurrences": occ,
                }
        finally:
            conn.close()

    def list_bugs(self) -> List[CrashReport]:
        """Lists all tracked bugs in repository."""
        return list(self._mock_db.values())


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="MiOS Kernel Fuzz Crash Deduplication & Bug Logger (T-558)")
    parser.add_argument("--log-file", metavar="PATH", help="Path to raw kernel serial / syzkaller log file")
    parser.add_argument("--db-url", help="PostgreSQL connection string (e.g. postgresql://user:pass@localhost:5432/mios)")
    parser.add_argument("--list", action="store_true", help="List all currently tracked bugs")
    parser.add_argument("--mock", action="store_true", help="Use in-memory database simulation")
    parser.add_argument("--json", action="store_true", help="Output results in JSON format")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    engine = CrashTriageEngine(mock=args.mock)

    try:
        if args.list:
            bugs = engine.list_bugs()
            data = [b.to_dict() for b in bugs]
            if args.json:
                print(json.dumps({"status": "ok", "bugs": data}, indent=2))
            else:
                print(f"Tracked Bugs ({len(bugs)}):")
                for b in bugs:
                    print(f"  [{b.crash_hash}] ({b.subsystem}) {b.title} (Occurrences: {b.occurrences}, Status: {b.status})")
            return 0

        if args.log_file:
            with open(args.log_file, "r", encoding="utf-8", errors="replace") as f:
                log_text = f.read()

            reports = engine.parse_log(log_text)
            recorded = []
            for r in reports:
                rec_res = engine.record_to_db(r, db_url=args.db_url)
                recorded.append(rec_res)

            if args.json:
                print(json.dumps({"status": "ok", "parsed_crashes": len(reports), "records": recorded}, indent=2))
            else:
                print(f"Processed {len(reports)} crash event(s):")
                for rec in recorded:
                    print(f"  [{rec['status']}] Hash: {rec['crash_hash']} (Occurrences: {rec['occurrences']}) - {rec.get('title', '')}")
            return 0

        # Default: list mock bugs
        bugs = engine.list_bugs()
        print(json.dumps({"status": "ok", "bugs": [b.to_dict() for b in bugs]}, indent=2))
        return 0

    except Exception as e:
        logger.error("Crash triage error: %s", e)
        if args.json:
            print(json.dumps({"status": "error", "error": str(e)}, indent=2))
        return 1


if __name__ == "__main__":
    sys.exit(main())
