.TH MIOS\-OPEN_URL 1 "" "MiOS 0.3.0" "MiOS Verbs"
.SH NAME
mios\-open_url \- A MiOS verb
.SH SYNOPSIS
.B mios open_url
.SH DESCRIPTION
A MiOS verb.
.SH FILES
.TP
.I /usr/share/mios/mios.toml
Declares this verb and the description shown above.
.SH SEE ALSO
.BR mios (1),
.BR mios.toml (5),
.BR mios (7)
