.TH MIOS\-POWERSHELL_RUN 1 "" "MiOS 0.3.0" "MiOS Verbs"
.SH NAME
mios\-powershell_run \- A MiOS verb
.SH SYNOPSIS
.B mios powershell_run
.SH DESCRIPTION
A MiOS verb.
.SH FILES
.TP
.I /usr/share/mios/mios.toml
Declares this verb and the description shown above.
.SH SEE ALSO
.BR mios (1),
.BR mios.toml (5),
.BR mios (7)
