.TH MIOS\-FILE_EDIT 1 "" "MiOS 0.3.0" "MiOS Verbs"
.SH NAME
mios\-file_edit \- A MiOS verb
.SH SYNOPSIS
.B mios file_edit
.SH DESCRIPTION
A MiOS verb.
.SH FILES
.TP
.I /usr/share/mios/mios.toml
Declares this verb and the description shown above.
.SH SEE ALSO
.BR mios (1),
.BR mios.toml (5),
.BR mios (7)
