#!/usr/bin/env bash
# /usr/libexec/mios/mios-hermes-workspace-firstboot.sh
#
# Seed the Hermes Workspace session password on first boot. The upstream
# image binds 0.0.0.0:3030 and requires HERMES_PASSWORD. By default we
# use the global MiOS password (mios.toml [identity].default_password,
# exported as MIOS_DEFAULT_PASSWORD via /etc/mios/install.env). Set
# MIOS_HERMES_WORKSPACE_PASSWORD in /etc/mios/install.env to override
# per-service; set MIOS_HERMES_WORKSPACE_PASSWORD=__random__ to force
# a random 48-hex-char value.
#
# Rotate: delete /etc/mios/hermes-workspace/workspace.env and restart
# this unit.
set -euo pipefail

# Pull MIOS_DEFAULT_PASSWORD + MIOS_HERMES_WORKSPACE_PASSWORD from
# install.env. The .service unit also passes them via EnvironmentFile=
# but we re-source here for direct-invocation paths (mios update).
[[ -r /etc/mios/install.env ]] && . /etc/mios/install.env

DEST=/etc/mios/hermes-workspace/workspace.env
install -d -m 0755 /etc/mios/hermes-workspace

if [[ -s "$DEST" ]] && grep -q '^HERMES_PASSWORD=' "$DEST" 2>/dev/null; then
    echo "[hermes-workspace-firstboot] $DEST already populated; nothing to do"
    exit 0
fi

PW="${MIOS_HERMES_WORKSPACE_PASSWORD:-${MIOS_DEFAULT_PASSWORD:-mios}}"
if [[ "$PW" == "__random__" ]]; then
    PW=$(openssl rand -hex 24 2>/dev/null || \
         head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')
    echo "[hermes-workspace-firstboot] MIOS_HERMES_WORKSPACE_PASSWORD=__random__ -> generated 48-char value"
fi

cat > "$DEST" <<EOF
# /etc/mios/hermes-workspace/workspace.env
# Generated by mios-hermes-workspace-firstboot.service on first boot.
# Read by both mios-hermes-workspace (login authentication) and any
# operator tooling that needs the workspace login password.
# Rotate by deleting this file + restarting mios-hermes-workspace-
# firstboot.service.

HERMES_PASSWORD=$PW
EOF
chmod 0640 "$DEST"
chown root:root "$DEST"

echo "[hermes-workspace-firstboot] wrote $DEST (rotate: rm + systemctl restart mios-hermes-workspace-firstboot.service)"
