#!/usr/bin/env bash
# /usr/libexec/mios/mios-hermes-workspace-firstboot.sh
#
# Generate the Hermes Workspace session password on first boot. The
# upstream image binds 0.0.0.0:3030 (non-loopback), which makes
# HERMES_PASSWORD REQUIRED -- without it the container exits with a
# clear "session password missing" error.
#
# Sentinel: /etc/mios/hermes-workspace/workspace.env -- delete the
# file + restart this unit to rotate the password.
set -euo pipefail

DEST=/etc/mios/hermes-workspace/workspace.env
install -d -m 0755 /etc/mios/hermes-workspace

if [[ -s "$DEST" ]] && grep -q '^HERMES_PASSWORD=' "$DEST" 2>/dev/null; then
    echo "[hermes-workspace-firstboot] $DEST already populated; nothing to do"
    exit 0
fi

# 24 random bytes -> 48 hex chars. Strong enough for a session
# password; rotate by deleting the file.
PW=$(openssl rand -hex 24 2>/dev/null || \
     head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')

cat > "$DEST" <<EOF
# /etc/mios/hermes-workspace/workspace.env
# Generated by mios-hermes-workspace-firstboot.service on first boot.
# Read by both mios-hermes-workspace (login authentication) and any
# operator tooling that needs the workspace login password.
# Rotate by deleting this file + restarting mios-hermes-workspace-
# firstboot.service.

HERMES_PASSWORD=$PW
EOF
chmod 0640 "$DEST"
chown root:root "$DEST"

echo "[hermes-workspace-firstboot] wrote $DEST (rotate: rm + systemctl restart mios-hermes-workspace-firstboot.service)"
